.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH blacs\(ulgridmap 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
blacs\(ulgridmap \- Maps available processes into BLACS process grid. 
.SH SYNOPSIS
.PP
\fBcall blacs\(ulgridmap\fR( \fIicontxt\fR, \fIusermap\fR, \fIldumap\fR, \fInprow\fR, \fInpcol\fR)
.SH INPUT PARAMETERS

.TP 10
\fBicontxt\fR
.NL
\fBINTEGER\fR.  Integer handle indicating the system context to be used in creating the BLACS context. Call \fBblacs\(ulget\fR to obtain a default system context.
.TP 10
\fBusermap\fR
.NL
\fBINTEGER\fR. Array, dimension (\fBldumap\fR, \fBnpcol\fR), indicating the process-to-grid mapping.
.TP 10
\fBldumap\fR
.NL
\fBINTEGER\fR.  Leading dimension of the 2D array \fBusermap\fR. \fBldumap\fR   \(>= \fBnprow\fR.
.TP 10
\fBnprow\fR
.NL
\fBINTEGER\fR. Indicates how many process rows the process grid should contain.
.TP 10
\fBnpcol\fR
.NL
\fBINTEGER\fR. Indicates how many process columns the process grid should contain.
.SH OUTPUT PARAMETERS

.TP 10
\fBicontxt\fR
.NL
\fBINTEGER\fR.  Integer handle to the created BLACS context.
