.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH ?spmv 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
?spmv \- Computes a matrix-vector product for complex vectors using a complex symmetric packed matrix.
.SH SYNOPSIS
.PP
\fBcall cspmv\fR( \fIuplo\fR, \fIn\fR, \fIalpha\fR, \fIap\fR, \fIx\fR, \fIincx\fR, \fIbeta\fR, \fIy\fR, \fIincy\fR)
.PP
\fBcall zspmv\fR( \fIuplo\fR, \fIn\fR, \fIalpha\fR, \fIap\fR, \fIx\fR, \fIincx\fR, \fIbeta\fR, \fIy\fR, \fIincy\fR)
.SH INPUT PARAMETERS

.TP 10
\fBuplo\fR
.NL
\fBCHARACTER*1\fR. Specifies whether the upper or lower triangular part of the matrix \fIa\fR is supplied in the packed array \fIap\fR.
.IP
If \fIuplo\fR = \fB\'U\'\fR or \fB\'u\'\fR, the upper triangular part of the matrix \fIa\fR is supplied in the array \fIap\fR. 
.IP
If \fIuplo\fR = \fB\'L\'\fR or \fB\'l\'\fR, the lower triangular part of the matrix \fIa\fR is supplied in the array \fIap\fR .
.TP 10
\fBn\fR
.NL
\fBINTEGER\fR.
.IP
Specifies the order of the matrix \fIa\fR.
.IP
The value of \fIn\fR must be at least zero.
.TP 10
\fBalpha\fR, \fBbeta\fR
.NL
\fBCOMPLEX\fR for \fBcspmv\fR
.IP
\fBCOMPLEX*16\fR for \fBzspmv\fR
.IP
Specify complex scalars \fIalpha\fR and \fIbeta\fR. When \fIbeta\fR is supplied as zero, then \fIy\fR need not be set on input.
.TP 10
\fBap\fR
.NL
\fBCOMPLEX\fR for \fBcspmv\fR
.IP
\fBCOMPLEX*16\fR for \fBzspmv\fR
.IP
Array, \fBDIMENSION\fR at least ((\fIn\fR*(\fIn\fR + 1))/2). Before entry, with \fIuplo\fR = \fB\'U\'\fR or \fB\'u\'\fR, the array \fIap\fR must contain the upper triangular part of the symmetric matrix packed sequentially, column-by-column, so that \fIap\fR(1) contains \fIA\fR(1, 1), \fIap\fR(2) and \fIap\fR(3) contain \fIA\fR(1, 2) and \fIA\fR(2, 2) respectively, and so on. Before entry, with \fIuplo\fR = \fB\'L\'\fR or \fB\'l\'\fR, the array \fIap\fR must contain the lower triangular part of the symmetric matrix packed sequentially, column-by-column, so that \fIap\fR(1) contains \fIa\fR(1, 1), \fIap\fR(2) and \fIap\fR(3) contain \fIa\fR(2, 1) and \fIa\fR(3, 1) respectively, and so on.
.TP 10
\fBx\fR
.NL
\fBCOMPLEX\fR for \fBcspmv\fR
.IP
\fBCOMPLEX*16\fR for \fBzspmv\fR
.IP
Array, \fBDIMENSION\fR at least \fB(1\fR + (\fIn\fR - \fB1)*abs\fR(\fIincx\fR\fB))\fR. Before entry, the incremented array \fBx\fR must contain the \fIn\fR-element vector \fIx\fR.
.TP 10
\fBincx\fR
.NL
\fBINTEGER\fR. Specifies the increment for the elements of \fIx\fR. The value of \fIincx\fR must not be zero.
.TP 10
\fBy\fR
.NL
\fBCOMPLEX\fR for \fBcspmv\fR
.IP
\fBCOMPLEX*16\fR for \fBzspmv\fR
.IP
Array, \fBDIMENSION\fR at least \fB(1\fR + (\fIn\fR - \fB1)*abs\fR(\fIincy\fR\fB))\fR. Before entry, the incremented array \fIy\fR must contain the \fIn\fR-element vector \fIy\fR.
.TP 10
\fBincy\fR
.NL
\fBINTEGER\fR. Specifies the increment for the elements of \fIy\fR. The value of \fIincy\fR must not be zero.
.SH OUTPUT PARAMETERS

.TP 10
\fBy\fR
.NL
Overwritten by the updated vector \fIy\fR.
