.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH ClearErrorCallBack 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
ClearErrorCallBack \- 
.SH SYNOPSIS
.PP
.B ! Fortran
.PP
\fIoldcallback\fR= \fBvmlclearerrorcallback\fR( )
.PP
.B /* C */
.PP
\fIoldcallback\fR= \fBvmlClearErrorCallBack\fR( \fBvoid\fR );
.SH OUTPUT PARAMETERS
.PP
.SB Name
.br
\h\'1\'\fBoldcallback\fR
.br
.SB Type
.br
\h\'2\'FORTRAN: \fBINTEGER\fR
.br
\h\'2\'C:\h\'7\'\fBint\fR
.br
.SB Description
.br
\h\'2\'FORTRAN: Address of the former callback function
.br
\h\'2\'C:\h\'7\'Pointer to the former callback function
