.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH Cosh 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
Cosh \- 
.SH SYNOPSIS
.PP
.B ! Fortran
.PP
\fBcall vscosh\fR( \fIn\fR, \fIa\fR, \fIy\fR)
.PP
\fBcall vdcosh\fR( \fIn\fR, \fIa\fR, \fIy\fR)
.PP
\fBcall vccosh\fR( \fIn\fR, \fIa\fR, \fIy\fR)
.PP
\fBcall vzcosh\fR( \fIn\fR, \fIa\fR, \fIy\fR)
.PP
.B /* C */
.PP
\fBvsCosh\fR( \fIn\fR, \fIa\fR, \fIy\fR);
.PP
\fBvdCosh\fR( \fIn\fR, \fIa\fR, \fIy\fR);
.PP
\fBvcCosh\fR( \fIn\fR, \fIa\fR, \fIy\fR);
.PP
\fBvzCosh\fR( \fIn\fR, \fIa\fR, \fIy\fR);
.SH INPUT PARAMETERS
.PP
.SB Name
.br
\h\'1\'\fBn\fR
.br
.SB Type
.br
\h\'2\'FORTRAN: \fBINTEGER\fR, \fBINTENT(IN)\fR
.br
\h\'2\'C:\h\'7\'\fBint\fR
.br
.SB Description
.br
\h\'1\'Specifies the number of elements to be calculated.
.PP
.SB Name
.br
\h\'1\'\fBa\fR
.br
.SB Type
.br
\h\'2\'FORTRAN: \fBREAL\fR, \fBINTENT(IN)\fR for \fBvscosh\fR
.br
\h\'11\'\fBDOUBLE PRECISION\fR, \fBINTENT(IN)\fR for \fBvdcosh\fR
.br
\h\'11\'\fBCOMPLEX\fR, \fBINTENT(IN)\fR for \fBvccosh\fR
.br
\h\'11\'\fBDOUBLE COMPLEX\fR, \fBINTENT(IN)\fR for \fBvzcosh\fR
.br
\h\'2\'C:\h\'7\'\fBconst float*\fR for \fBvsCosh\fR
.br
\h\'11\'\fBconst double*\fR for \fBvdCosh\fR
.br
\h\'11\'\fBconst MKL\(ulComplex8*\fR for \fBvcCosh\fR
.br
\h\'11\'\fBconst MKL\(ulComplex16*\fR for \fBvzCosh\fR
.br
.SB Description
.br
\h\'2\'FORTRAN: Array, specifies the input vector \fBa\fR.
.br
\h\'2\'C:\h\'7\'Pointer to an array that contains the input vector \fBa\fR.
.PP
.B NOTE:
Overflow can occur also in \fBCosh\fR complex function, but the exact formula is beyond the scope of this document.
.SH OUTPUT PARAMETERS
.PP
.SB Name
.br
\h\'1\'\fBy\fR
.br
.SB Type
.br
\h\'2\'FORTRAN: \fBREAL\fR for \fBvscosh\fR
.br
\h\'11\'\fBDOUBLE PRECISION\fR for \fBvdcosh\fR
.br
\h\'11\'\fBCOMPLEX\fR for \fBvccosh\fR
.br
\h\'11\'\fBDOUBLE COMPLEX\fR for \fBvzcosh\fR
.br
\h\'2\'C:\h\'7\'\fBfloat*\fR for \fBvsCosh\fR
.br
\h\'11\'\fBdouble*\fR for \fBvdCosh\fR
.br
\h\'11\'\fBMKL\(ulComplex8*\fR for \fBvcCosh\fR
.br
\h\'11\'\fBMKL\(ulComplex16*\fR for \fBvzCosh\fR
.br
.SB Description
.br
\h\'2\'FORTRAN: Array, specifies the output vector \fBy\fR.
.br
\h\'2\'C:\h\'7\'Pointer to an array that contains the output vector \fBy\fR.
