.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH dcabs1 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
dcabs1 \- Computes absolute value of double complex number.
.SH SYNOPSIS
.PP
.B Fortran 77
.PP
\fIres\fR= \fBdcabs1\fR(\fIz\fR)
.PP
.B Fortran 95
.PP
\fIres\fR= \fBdcabs1\fR(\fIz\fR)
.SH INPUT PARAMETERS

.TP 10
\fBz\fR
.NL
\fBDOUBLE COMPLEX\fR scalar.
.SH OUTPUT PARAMETERS

.TP 10
\fBres\fR
.NL
\fBDOUBLE PRECISION\fR.
.IP
Contains the absolute value of a double complex number \fIz\fR.
