.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH ?dotc 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
?dotc \- Computes a dot product of a conjugated vector with another vector.
.SH SYNOPSIS
.PP
.B Fortran 77
.PP
\fIres\fR= \fBcdotc\fR(\fIn\fR, \fIx\fR, \fIincx\fR, \fIy\fR, \fIincy\fR)
.PP
\fIres\fR= \fBzdotc\fR(\fIn\fR, \fIx\fR, \fIincx\fR, \fIy\fR, \fIincy\fR)
.PP
.B Fortran 95
.PP
\fIres\fR= \fBdotc\fR(\fIx\fR, \fIy\fR)
.SH INPUT PARAMETERS

.TP 10
\fBn\fR
.NL
\fBINTEGER\fR.  Specifies the order of vectors \fIx\fR and \fIy\fR. 
.TP 10
\fBx\fR
.NL
\fBCOMPLEX\fR for \fBcdotc\fR
.IP
\fBDOUBLE COMPLEX\fR for \fBzdotc\fR
.IP
Array, \fBDIMENSION\fR at least (1 + (\fIn\fR -1)*abs(\fIincx\fR)).
.TP 10
\fBincx\fR
.NL
\fBINTEGER\fR.  Specifies the increment for the elements of \fIx\fR.
.TP 10
\fBy\fR
.NL
\fBCOMPLEX\fR for \fBcdotc\fR
.IP
\fBDOUBLE COMPLEX\fR for \fBzdotc\fR
.IP
Array, \fBDIMENSION\fR at least (1 + (\fIn\fR -1)*abs(\fIincy\fR)).
.TP 10
\fBincy\fR
.NL
\fBINTEGER\fR.  Specifies the increment for the elements of \fIy\fR. 
.SH OUTPUT PARAMETERS

.TP 10
\fBres\fR
.NL
\fBCOMPLEX\fR for \fBcdotc\fR
.IP
\fBDOUBLE COMPLEX\fR for \fBzdotc\fR
.IP
Contains the result of the dot product of the conjugated \fIx\fR and unconjugated \fIy\fR, if \fIn\fR is positive. Otherwise, \fIres\fR contains 0.
.SH FORTRAN 95 INTERFACE NOTES
.PP
.PP
Routines in Fortran 95 interface have fewer arguments in the calling sequence than their Fortran 77   counterparts. For general conventions applied to skip redundant or reconstructible arguments, see Fortran 95 Interface Conventions.
.PP
Specific details for the routine \fBdotc\fR interface are the following:
.TP 10
\fBx\fR
.NL
Holds the vector of length(\fIn\fR).
.TP 10
\fBy\fR
.NL
Holds the vector of length (\fIn\fR).
