.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH ErrorClass 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
ErrorClass \- Checks if the status reflects an error of a predefined class.
.SH SYNOPSIS
.PP
.B ! Fortran
.PP
\fBPredicate\fR = \fBDftiErrorClass\fR( \fIStatus\fR, \fIError\(ulClass\fR)
.PP
.B /* C */
.PP
\fBpredicate\fR = \fBDftiErrorClass\fR( \fIstatus\fR, \fIerror\(ulclass\fR);
.PP

.br
//Fortran interface
.br
INTERFACE DftiErrorClass
.br
//Note that the body provided here is to illustrate the different
.br
//argument list and types of dummy arguments. The interface
.br
//does not guarantee what the actual function names are.
.br
//Users can only rely on the function name following the
.br
//keyword INTERFACE
.br
FUNCTION some\(ulactual\(ulfunction\(ul8( Status, Error\(ulClass )
.br
LOGICAL some\(ulactual\(ulfunction\(ul8
.br
INTEGER, INTENT(IN) :: Status, Error\(ulClass
.br
END FUNCTION some\(ulactual\(ulfunction\(ul8
.br
END INTERFACE DftiErrorClass 
.br
   
.br
/* C prototype */
.br
long DftiErrorClass( long , long );
