.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH getcpufrequency 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
getcpufrequency \- Returns CPU frequency value in GHz.
.SH SYNOPSIS
.PP
\fIval\fR= \fBgetcpufrequency()\fR
.SH OUTPUT PARAMETERS

.TP 10
\fBval\fR
.NL
\fBDOUBLE PRECISION\fR. CPU frequency value in GHz. 
