.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH getcpuclocks 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
getcpuclocks \- Returns full precision elapsed CPU clocks.
.SH SYNOPSIS
.PP
\fBgetcpuclocks\fR( \fIclocks\fR)
.SH OUTPUT PARAMETERS

.TP 10
\fBclocks\fR
.NL
\fBINTEGER*8\fR. Elapsed CPU clocks.
