.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH GetErrorCallBack 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
GetErrorCallBack \- 
.SH SYNOPSIS
.PP
.B ! Fortran
.PP
\fIcallback\fR= \fBvmlgeterrorcallback\fR( )
.PP
.B /* C */
.PP
\fIcallback\fR= \fBvmlGetErrorCallBack\fR( \fBvoid\fR );
.SH OUTPUT PARAMETERS
.PP
.SB Name
.br
\h\'1\'\fBcallback\fR
.br
.SB Type
.br
.SB Description
.br
\h\'2\'FORTRAN: Address of the callback function
.br
\h\'2\'C:\h\'7\'Pointer to the callback function
