.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH Hypot 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
Hypot \- 
.SH SYNOPSIS
.PP
.B ! Fortran
.PP
\fBcall vshypot\fR( \fIn\fR, \fIa\fR, \fIb\fR, \fIy\fR)
.PP
\fBcall vdhypot\fR( \fIn\fR, \fIa\fR, \fIb\fR, \fIy\fR)
.PP
.B /* C */
.PP
\fBvsHypot\fR( \fIn\fR, \fIa\fR, \fIb\fR, \fIy\fR);
.PP
\fBvdHypot\fR( \fIn\fR, \fIa\fR, \fIb\fR, \fIy\fR);
.SH INPUT PARAMETERS
.PP
.SB Name
.br
\h\'1\'\fIn\fR
.br
.SB Type
.br
\h\'2\'FORTRAN: \fBINTEGER\fR, \fBINTENT(IN)\fR
.br
\h\'2\'C:\h\'7\'\fBint\fR
.br
.SB Description
.br
\h\'1\'Number of elements to be calculated. 
.PP
.SB Name
.br
\h\'1\'\fIa\fR,\fIb\fR
.br
.SB Type
.br
\h\'2\'FORTRAN: \fBREAL\fR, \fBINTENT(IN)\fR for \fBvshypot\fR
.br
\h\'11\'\fBDOUBLE PRECISION\fR, \fBINTENT(IN)\fR for \fBvdhypot\fR
.br
\h\'2\'C:\h\'7\'\fBconst float*\fR for \fBvsHypot\fR
.br
\h\'11\'\fBconst double*\fR for \fBvdHypot\fR
.br
.SB Description
.br
\h\'2\'FORTRAN: Arrays that specify the input vectors \fIa\fR and \fIb\fR
.br
\h\'2\'C:\h\'7\'Pointers to arrays that contain the input vectors \fBa\fR and \fIb\fR.
.SH OUTPUT PARAMETERS
.PP
.SB Name
.br
\h\'1\'\fIy\fR
.br
.SB Type
.br
\h\'2\'FORTRAN: \fBREAL\fR for \fBvshypot\fR
.br
\h\'11\'\fBDOUBLE PRECISION\fR for \fBvdhypot\fR
.br
\h\'2\'C:\h\'7\'\fBfloat*\fR for \fBvsHypot\fR
.br
\h\'11\'\fBdouble*\fR for \fBvdHypot\fR
.br
.SB Description
.br
\h\'2\'FORTRAN: Array, specifies the output vector \fBy\fR.
.br
\h\'2\'C:\h\'7\'Pointer to an array that contains the output vector \fBy\fR.
