.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH ?isnan 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
?isnan \- Tests input for NaN.
.SH SYNOPSIS
.PP
\fIval\fR= \fBsisnan\fR( \fIsin\fR)
.PP
\fIval\fR= \fBdisnan\fR( \fIdin\fR)
.SH INPUT PARAMETERS

.TP 10
\fBsin\fR
.NL
\fBREAL\fR for \fBsisnan\fR
.IP
Input to test for \fBNaN\fR.
.TP 10
\fBdin\fR
.NL
\fBDOUBLE PRECISION\fR for \fBdisnan\fR
.IP
Input to test for \fBNaN\fR.
.SH OUTPUT PARAMETERS

.TP 10
\fBval\fR
.NL
\fBLogical\fR. Result of the test. 
