.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH ?ladiv 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
?ladiv \- Performs complex division in real arithmetic, avoiding unnecessary overflow.
.SH SYNOPSIS
.PP
\fBcall sladiv\fR( \fIa\fR, \fIb\fR, \fIc\fR, \fId\fR, \fIp\fR, \fIq\fR)
.PP
\fBcall dladiv\fR( \fIa\fR, \fIb\fR, \fIc\fR, \fId\fR, \fIp\fR, \fIq\fR)
.PP
\fIres\fR= \fBcladiv\fR( \fIx\fR, \fIy\fR)
.PP
\fIres\fR= \fBzladiv\fR( \fIx\fR, \fIy\fR)
.SH INPUT PARAMETERS

.TP 10
\fBa\fR, \fBb\fR, \fBc\fR, \fBd\fR
.NL
\fBREAL\fR for \fBsladiv\fR
.IP
\fBDOUBLE PRECISION\fR for \fBdladiv\fR
.IP
The scalars \fIa\fR, \fIb\fR, \fIc\fR, and \fId\fR in the above expression (for real flavors only).
.TP 10
\fBx\fR, \fBy\fR
.NL
\fBCOMPLEX\fR for \fBcladiv\fR
.IP
\fBCOMPLEX*16\fR for \fBzladiv\fR
.IP
The complex scalars \fIx\fR and \fIy\fR (for complex flavors only).
.SH OUTPUT PARAMETERS

.TP 10
\fBp\fR, \fBq\fR
.NL
\fBREAL\fR for \fBsladiv\fR
.IP
\fBDOUBLE PRECISION\fR for \fBdladiv\fR
.IP
The scalars \fIp\fR and \fIq\fR in the above expression (for real flavors only).
.TP 10
\fBres\fR
.NL
\fBCOMPLEX\fR for \fBcladiv\fR
.IP
\fBDOUBLE COMPLEX\fR for \fBzladiv\fR
.IP
Contains the result of division \fIx\fR /  \fIy\fR.
