.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH ?lahr2 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
?lahr2 \- Reduces the specified number of first columns of a general rectangular matrix A so that elements below the specified subdiagonal are zero, and returns auxiliary matrices which are needed to apply the transformation to the unreduced part of A.
.SH SYNOPSIS
.PP
\fBcall slahr2\fR( \fIn\fR, \fIk\fR, \fInb\fR, \fIa\fR, \fIlda\fR, \fItau\fR, \fIt\fR, \fIldt\fR, \fIy\fR, \fIldy\fR)
.PP
\fBcall dlahr2\fR( \fIn\fR, \fIk\fR, \fInb\fR, \fIa\fR, \fIlda\fR, \fItau\fR, \fIt\fR, \fIldt\fR, \fIy\fR, \fIldy\fR)
.PP
\fBcall clahr2\fR( \fIn\fR, \fIk\fR, \fInb\fR, \fIa\fR, \fIlda\fR, \fItau\fR, \fIt\fR, \fIldt\fR, \fIy\fR, \fIldy\fR)
.PP
\fBcall zlahr2\fR( \fIn\fR, \fIk\fR, \fInb\fR, \fIa\fR, \fIlda\fR, \fItau\fR, \fIt\fR, \fIldt\fR, \fIy\fR, \fIldy\fR)
.SH INPUT PARAMETERS

.TP 10
\fBn\fR
.NL
\fBINTEGER\fR. The order of the matrix \fIA\fR (\fIn \fR\(>= 0). 
.TP 10
\fBk\fR
.NL
\fBINTEGER\fR. The offset for the reduction. Elements below the \fIk\fR-th subdiagonal in the first \fInb\fR columns are reduced to zero (\fBk\fR< \fBn\fR). 
.TP 10
\fBnb\fR
.NL
\fBINTEGER\fR. The number of columns to be reduced. 
.TP 10
\fBa\fR
.NL
\fBREAL\fR for \fBslahr2\fR
.IP
\fBDOUBLE PRECISION\fR for \fBdlahr2\fR
.IP
\fBCOMPLEX\fR for \fBclahr2\fR
.IP
\fBCOMPLEX*16\fR for \fBzlahr2\fR.
.IP
Array, \fBDIMENSION\fR (\fIlda\fR, \fIn\fR-\fIk\fR+1) contains the \fIn\fR-by-(\fIn\fR-\fIk\fR+1) general matrix \fIA\fR to be reduced.
.TP 10
\fBlda\fR
.NL
\fBINTEGER\fR. The first dimension of the array \fBa\fR; \fBlda \fR\(>= max(1, \fBn\fR).
.TP 10
\fBldt\fR
.NL
\fBINTEGER\fR. The first dimension of the output array \fBt\fR; \fBldt \fR\(>=\fB nb\fR.
.TP 10
\fBldy\fR
.NL
\fBINTEGER\fR. The first dimension of the output array \fBy\fR; \fBldy \fR\(>=\fB n\fR.
.SH OUTPUT PARAMETERS

.TP 10
\fBa\fR
.NL
On exit, the elements on and above the \fIk\fR-th subdiagonal in the first \fInb\fR columns are overwritten with the corresponding elements of the reduced matrix; the elements below the \fIk\fR-th subdiagonal, with the array \fItau\fR, represent the matrix \fIQ\fR as a product of elementary reflectors. The other columns of \fIa\fR are unchanged. See \fIApplication Notes\fRbelow.
.TP 10
\fBtau\fR
.NL
\fBREAL\fR for \fBslahr2\fR
.IP
\fBDOUBLE PRECISION\fR for \fBdlahr2\fR
.IP
\fBCOMPLEX\fR for \fBclahr2\fR
.IP
\fBCOMPLEX*16\fR for \fBzlahr2\fR.
.IP
Array, \fBDIMENSION\fR (\fInb\fR). 
.IP
Contains scalar factors of the elementary reflectors.
.TP 10
\fBt\fR, \fBy\fR
.NL
\fBREAL\fR for \fBslahr2\fR
.IP
\fBDOUBLE PRECISION\fR for \fBdlahr2\fR
.IP
\fBCOMPLEX\fR for \fBclahr2\fR
.IP
\fBCOMPLEX*16\fR for \fBzlahr2\fR.
.IP
Arrays, dimension \fIt\fR(\fIldt\fR, \fInb\fR), \fIy\fR(\fIldy\fR, \fInb\fR). 
.IP
The array \fIt\fR contains upper triangular matrix \fIT\fR. 
.IP
The array \fIy\fR contains the \fIn\fR-by-\fInb\fR matrix \fIY\fR . 
