.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH ?lapy3 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
?lapy3 \- Returns sqrt(\fIx\fR**2+\fIy\fR**2+\fIz\fR**2).
.SH SYNOPSIS
.PP
\fIval\fR= \fBslapy3\fR( \fIx\fR, \fIy\fR, \fIz\fR)
.PP
\fIval\fR= \fBdlapy3\fR( \fIx\fR, \fIy\fR, \fIz\fR)
.SH INPUT PARAMETERS

.TP 10
\fBx\fR, \fBy\fR, \fBz\fR
.NL
\fBREAL\fR for \fBslapy3\fR
.IP
\fBDOUBLE PRECISION\fR for \fBdlapy3\fR
.IP
Specify the input values \fIx\fR, \fIy\fR and \fIz\fR.
.SH OUTPUT PARAMETERS

.TP 10
\fBval\fR
.NL
\fBREAL\fR for \fBslapy3\fR
.IP
\fBDOUBLE PRECISION\fR for \fBdlapy3\fR.
.IP
Value returned by the function.
