.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH ?largv 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
?largv \- Generates a vector of plane rotations with real cosines and real/complex sines.
.SH SYNOPSIS
.PP
\fBcall slargv\fR( \fIn\fR, \fIx\fR, \fIincx\fR, \fIy\fR, \fIincy\fR, \fIc\fR, \fIincc\fR)
.PP
\fBcall dlargv\fR( \fIn\fR, \fIx\fR, \fIincx\fR, \fIy\fR, \fIincy\fR, \fIc\fR, \fIincc\fR)
.PP
\fBcall clargv\fR( \fIn\fR, \fIx\fR, \fIincx\fR, \fIy\fR, \fIincy\fR, \fIc\fR, \fIincc\fR)
.PP
\fBcall zlargv\fR( \fIn\fR, \fIx\fR, \fIincx\fR, \fIy\fR, \fIincy\fR, \fIc\fR, \fIincc\fR)
.SH INPUT PARAMETERS

.TP 10
\fBn\fR
.NL
\fBINTEGER\fR. The number of plane rotations to be generated.
.TP 10
\fBx\fR, \fBy\fR
.NL
\fBREAL\fR for \fBslargv\fR
.IP
\fBDOUBLE PRECISION\fR for \fBdlargv\fR
.IP
\fBCOMPLEX\fR for \fBclargv\fR
.IP
\fBCOMPLEX*16\fR for \fBzlargv\fR
.IP
Arrays, \fBDIMENSION\fR (1+(\fIn\fR-1)*\fIincx\fR) and (1+(\fIn\fR-1)*\fIincy\fR), respectively. On entry, the vectors \fIx\fR and \fIy\fR.
.TP 10
\fBincx\fR
.NL
\fBINTEGER\fR. The increment between elements of \fIx\fR. 
.IP
\fIincx\fR > 0.
.TP 10
\fBincy\fR
.NL
\fBINTEGER\fR. The increment between elements of \fIy\fR. 
.IP
\fIincy\fR > 0.
.TP 10
\fBincc\fR
.NL
\fBINTEGER\fR. The increment between elements of the output array \fIc\fR. \fIincc\fR > 0.
.SH OUTPUT PARAMETERS

.TP 10
\fBx\fR
.NL
On exit, \fIx\fR(\fIi\fR) is overwritten by \fIa\fR(\fIi\fR)  (for real flavors), or by \fIr\fR(\fIi\fR) (for complex flavors), for \fIi\fR = 1,...,\fIn\fR.
.TP 10
\fBy\fR
.NL
On exit, the sines \fIs\fR(\fIi\fR) of the plane rotations.
.TP 10
\fBc\fR
.NL
\fBREAL\fR for \fBslargv\fR/\fBclargv\fR
.IP
\fBDOUBLE PRECISION\fR for \fBdlargv\fR/\fBzlargv\fR
.IP
Array, \fBDIMENSION\fR (1+(\fIn\fR-1)*\fIincc\fR). The cosines of the plane rotations.
