.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH ?lasd0 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
?lasd0 \- Computes the singular values of a real upper bidiagonal \fIn\fR-by-\fIm\fR matrix B with diagonal \fId\fR and off-diagonal \fIe\fR. Used by \fB?bdsdc\fR.
.SH SYNOPSIS
.PP
\fBcall slasd0\fR( \fIn\fR, \fIsqre\fR, \fId\fR, \fIe\fR, \fIu\fR, \fIldu\fR, \fIvt\fR, \fIldvt\fR, \fIsmlsiz\fR, \fIiwork\fR, \fIwork\fR, \fIinfo\fR)
.PP
\fBcall dlasd0\fR( \fIn\fR, \fIsqre\fR, \fId\fR, \fIe\fR, \fIu\fR, \fIldu\fR, \fIvt\fR, \fIldvt\fR, \fIsmlsiz\fR, \fIiwork\fR, \fIwork\fR, \fIinfo\fR)
.SH INPUT PARAMETERS

.TP 10
\fBn\fR
.NL
\fBINTEGER\fR. On entry, the row dimension of the upper bidiagonal matrix. This is also the dimension of the main diagonal array \fId\fR.
.TP 10
\fBsqre\fR
.NL
\fBINTEGER\fR. Specifies the column dimension of the bidiagonal matrix. 
.IP
If \fIsqre\fR = 0: the bidiagonal matrix has column dimension \fIm\fR = \fIn\fR.
.IP
If \fIsqre\fR = 1: the bidiagonal matrix has column dimension \fIm\fR = \fIn\fR+1.
.TP 10
\fBd\fR
.NL
\fBREAL\fR for \fBslasd0\fR
.IP
\fBDOUBLE PRECISION\fR for \fBdlasd0\fR
.IP
Array, \fBDIMENSION\fR (\fIn\fR). On entry, \fId\fR contains the main diagonal of the bidiagonal matrix.
.TP 10
\fBe\fR
.NL
\fBREAL\fR for \fBslasd0\fR
.IP
\fBDOUBLE PRECISION\fR for \fBdlasd0\fR
.IP
Array, \fBDIMENSION\fR (\fIm\fR-1). Contains the subdiagonal entries of the bidiagonal matrix. On exit, \fIe\fR is destroyed.
.TP 10
\fBldu\fR
.NL
\fBINTEGER\fR. On entry, leading dimension of the output array \fIu\fR.
.TP 10
\fBldvt\fR
.NL
\fBINTEGER\fR. On entry, leading dimension of the output array \fIvt\fR.
.TP 10
\fBsmlsiz\fR
.NL
\fBINTEGER\fR. On entry, maximum size of the subproblems at the bottom of the computation tree.
.TP 10
\fBiwork\fR
.NL
\fBINTEGER\fR. 
.IP
Workspace array, \fBdimension\fR must be at least (8\fIn\fR).
.TP 10
\fBwork\fR
.NL
\fBREAL\fR for \fBslasd0\fR
.IP
\fBDOUBLE PRECISION\fR for \fBdlasd0\fR
.IP
Workspace array, \fBdimension\fR must be at least (3\fIm\fR**2+2\fIm\fR).
.SH OUTPUT PARAMETERS

.TP 10
\fBd\fR
.NL
On exit \fId\fR, If \fIinfo\fR = 0, contains singular values of the bidiagonal matrix.
.TP 10
\fBu\fR
.NL
\fBREAL\fR for \fBslasd0\fR
.IP
\fBDOUBLE PRECISION\fR for \fBdlasd0\fR
.IP
Array, \fBDIMENSION\fR at least (\fIldq\fR, \fIn\fR). On exit, \fIu\fR contains the left singular vectors.
.TP 10
\fBvt\fR
.NL
\fBREAL\fR for \fBslasd0\fR
.IP
\fBDOUBLE PRECISION\fR for \fBdlasd0\fR
.IP
Array, \fBDIMENSION\fR at least (\fIldvt\fR, \fIm\fR). On exit, \fIvt\fR\' contains the right singular vectors.
.TP 10
\fBinfo\fR
.NL
\fBINTEGER\fR. 
.IP
If \fIinfo\fR = 0: successful exit. 
.IP
If \fIinfo\fR = -\fIi\fR < 0, the \fIi\fR-th argument had an illegal value. 
.IP
If \fIinfo\fR = 1, an singular value did not converge.
