.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH lsamen 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
lsamen \- Tests two character strings for equality regardless of case.
.SH SYNOPSIS
.PP
\fIval\fR= \fBlsamen\fR(\fIn\fR, \fIca\fR, \fIcb\fR)
.SH INPUT PARAMETERS

.TP 10
\fBn\fR
.NL
\fBINTEGER\fR. The number of characters in \fIca\fR and \fIcb\fR to be compared. 
.TP 10
\fBca\fR, \fBcb\fR
.NL
\fBCHARACTER*(*)\fR. Specify two character strings of length at least \fIn\fR to be compared. Only the first \fIn\fR characters of each string will be accessed.
.SH OUTPUT PARAMETERS

.TP 10
\fBval\fR
.NL
\fBLOGICAL\fR. Result of the comparison.
