.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH mkl\(ulget\(uldynamic 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
mkl\(ulget\(uldynamic \- Returns current value of \fBMKL\(ulDYNAMIC\fR variable.
.SH SYNOPSIS
.PP
.B ! Fortran
.PP
\fBret = mkl\(ulget\(uldynamic\fR()
.PP
.B /* C */
.PP
\fBint mkl\(ulget\(uldynamic\fR();
.SH RETURN VALUES
.PP

.TP 10
\fB1\fR
.NL
Indicates \fBMKL\(ulDYNAMIC\fR is true.
.TP 10
\fB0\fR
.NL
Indicates \fBMKL\(ulDYNAMIC\fR is false.
