.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH MKL\(ulfree 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
MKL\(ulfree \- Frees the aligned memory buffer allocated by MKL\(ulmalloc.
.SH SYNOPSIS
.PP
.B ! Fortran
.PP
\fBCALL MKL\(ulFREE\fR( \fIptr\fR)
.PP
.B /* C */
.PP
\fBvoid* \fR\fBMKL\(ulfree\fR( \fBvoid* \fR\fIptr\fR);
