.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH mkl\(ulget\(ulmax\(ulthreads 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
mkl\(ulget\(ulmax\(ulthreads \- Inquires about the number of threads targeted for parallelism.
.SH SYNOPSIS
.PP
.B ! Fortran
.PP
\fBnum = mkl\(ulget\(ulmax\(ulthreads\fR()
.PP
.B /* C */
.PP
\fBint mkl\(ulget\(ulmax\(ulthreads\fR();
.SH RETURN VALUES
.PP
.PP
The output is \fBINTEGER\fR equal to the number of threads.
