.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH mkl\(ulcvt\(ulto\(ulnull\(ulterminated\(ulstr 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
mkl\(ulcvt\(ulto\(ulnull\(ulterminated\(ulstr \- Passes character strings from Fortran routines to C routines.
.SH SYNOPSIS
.PP
\fBmkl\(ulcvt\(ulto\(ulnull\(ulterminated\(ulstr\fR (\fIdestStr\fR, \fIdestLen\fR, \fIsrcStr\fR)
.SH INPUT PARAMETERS

.TP 10
\fBdestLen\fR
.NL
\fBINTEGER\fR. Length of the output array \fIdestStr\fR.
.TP 10
\fBsrcStr\fR
.NL
\fBSTRING\fR. Input string.
.SH OUTPUT PARAMETERS

.TP 10
\fBdestStr\fR
.NL
\fBINTEGER\fR. One-dimensional array of integer.
