.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH p?lasmsub 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
p?lasmsub \- Looks for a small subdiagonal element from the bottom of the matrix that it can safely set to zero.
.SH SYNOPSIS
.PP
\fBcall pslasmsub\fR(\fIa\fR, \fIdesca\fR, \fIi\fR, \fIl\fR, \fIk\fR, \fIsmlnum\fR, \fIbuf\fR, \fIlwork\fR)
.PP
\fBcall pdlasmsub\fR(\fIa\fR, \fIdesca\fR, \fIi\fR, \fIl\fR, \fIk\fR, \fIsmlnum\fR, \fIbuf\fR, \fIlwork\fR)
.SH INPUT PARAMETERS

.TP 10
\fBa\fR
.NL
(global)
.IP
\fBREAL\fR for \fBpslasmsub\fR
.IP
\fBDOUBLE PRECISION\fR for \fBpdlasmsub\fR
.IP
Array, \fBDIMENSION\fR(\fIdesca\fR(\fIlld\(ul\fR),*). 
.IP
On entry, the Hessenberg matrix whose tridiagonal part is being scanned. Unchanged on exit.
.TP 10
\fBdesca\fR
.NL
(global and local) \fBINTEGER\fR. 
.IP
Array of \fBDIMENSION\fR (\fIdlen\(ul\fR). The array descriptor for the distributed matrix \fIA\fR.
.TP 10
\fBi\fR
.NL
(global) \fBINTEGER\fR. 
.IP
The global location of the bottom of the unreduced submatrix of \fIA\fR. Unchanged on exit.
.TP 10
\fBl\fR
.NL
(global) \fBINTEGER\fR. 
.IP
The global location of the top of the unreduced submatrix of \fIA\fR. 
.IP
Unchanged on exit.
.TP 10
\fBsmlnum\fR
.NL
(global)
.IP
\fBREAL\fR for \fBpslasmsub\fR
.IP
\fBDOUBLE PRECISION\fR for \fBpdlasmsub\fR
.IP
On entry, a ``small number'' for the given matrix. Unchanged on exit.
.TP 10
\fBlwork\fR
.NL
(global) \fBINTEGER\fR. 
.IP
On exit, \fIlwork\fR is the size of the work buffer. 
.IP
This must be at least 2*ceil(ceil((\fIi-l)/hbl\fR )/ lcm(\fInprow\fR,\fInpcol\fR)). Here \fBlcm\fR is least common multiple, and \fInprow\fR\fIx\fR\fInpcol\fR is the logical grid size.
.SH OUTPUT PARAMETERS

.TP 10
\fBk\fR
.NL
(global) \fBINTEGER\fR. 
.IP
On exit, this yields the bottom portion of the unreduced submatrix. This will satisfy: \fIl\fR \(<= \fIm\fR \(<= \fIi\fR-1. 
.TP 10
\fBbuf\fR
.NL
(local).
.IP
\fBREAL\fR for \fBpslasmsub\fR
.IP
\fBDOUBLE PRECISION\fR for \fBpdlasmsub\fR
.IP
Array of size \fIlwork\fR.
