.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH Pow3o2 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
Pow3o2 \- 
.SH SYNOPSIS
.PP
.B ! Fortran
.PP
\fBcall vspow3o2\fR( \fIn\fR, \fIa\fR, \fIy\fR)
.PP
\fBcall vdpow3o2\fR( \fIn\fR, \fIa\fR, \fIy\fR)
.PP
.B /* C */
.PP
\fBvsPow3o2\fR( \fIn\fR, \fIa\fR, \fIy\fR);
.PP
\fBvdPow3o2\fR( \fIn\fR, \fIa\fR, \fIy\fR);
.SH INPUT PARAMETERS
.PP
.SB Name
.br
\h\'1\'\fIn\fR
.br
.SB Type
.br
\h\'2\'FORTRAN: \fBINTEGER\fR, \fBINTENT(IN)\fR
.br
\h\'2\'C:\h\'7\'\fBint\fR
.br
.SB Description
.br
\h\'1\'Specifies the number of elements to be calculated. 
.PP
.SB Name
.br
\h\'1\'\fIa\fR, \fIb\fR
.br
.SB Type
.br
\h\'2\'FORTRAN: \fBREAL\fR, \fBINTENT(IN)\fR for \fBvspow3o2\fR
.br
\h\'11\'\fBDOUBLE PRECISION\fR, \fBINTENT(IN)\fR for \fBvdpow3o2\fR
.br
\h\'2\'C:\h\'7\'\fBconst float*\fR for \fBvsPow3o2\fR
.br
\h\'11\'\fBconst double*\fR for \fBvdPow3o2\fR
.br
.SB Description
.br
\h\'2\'FORTRAN: Arrays, specify the input vector \fBa\fR.
.br
\h\'2\'C:\h\'7\'Pointers to arrays that contain the input vector \fBa\fR.
.SH OUTPUT PARAMETERS
.PP
.SB Name
.br
\h\'1\'\fIy\fR
.br
.SB Type
.br
\h\'2\'FORTRAN: \fBREAL\fR for \fBvspow3o2\fR
.br
\h\'11\'\fBDOUBLE PRECISION\fR for \fBvdpow3o2\fR
.br
\h\'2\'C:\h\'7\'\fBfloat*\fR for \fBvsPow3o2\fR
.br
\h\'11\'\fBdouble*\fR for \fBvdPow3o2\fR
.br
.SB Description
.br
\h\'2\'FORTRAN: Array, specifies the output vector \fBy\fR.
.br
\h\'2\'C:\h\'7\'Pointer to an array that contains the output vector \fBy\fR.
