.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH Powx 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
Powx \- 
.SH SYNOPSIS
.PP
.B ! Fortran
.PP
\fBcall vspowx\fR( \fIn\fR, \fIa\fR, \fIb\fR, \fIy\fR)
.PP
\fBcall vdpowx\fR( \fIn\fR, \fIa\fR, \fIb\fR, \fIy\fR)
.PP
\fBcall vcpowx\fR( \fIn\fR, \fIa\fR, \fIb\fR, \fIy\fR)
.PP
\fBcall vzpowx\fR( \fIn\fR, \fIa\fR, \fIb\fR, \fIy\fR)
.PP
.B /* C */
.PP
\fBvsPowx\fR( \fIn\fR, \fIa\fR, \fIb\fR, \fIy\fR);
.PP
\fBvdPowx\fR( \fIn\fR, \fIa\fR, \fIb\fR, \fIy\fR);
.PP
\fBvcPowx\fR( \fIn\fR, \fIa\fR, \fIb\fR, \fIy\fR);
.PP
\fBvzPowx\fR( \fIn\fR, \fIa\fR, \fIb\fR, \fIy\fR);
.SH INPUT PARAMETERS
.PP
.SB Name
.br
\h\'1\'\fBn\fR
.br
.SB Type
.br
\h\'2\'FORTRAN: \fBINTEGER\fR, \fBINTENT(IN)\fR
.br
\h\'2\'C:\h\'7\'\fBint\fR
.br
.SB Description
.br
\h\'1\'Number of elements to be calculated. 
.PP
.SB Name
.br
\h\'1\'\fBa\fR
.br
.SB Type
.br
\h\'2\'FORTRAN: \fBREAL\fR, \fBINTENT(IN)\fR for \fBvspowx\fR
.br
\h\'11\'\fBDOUBLE PRECISION\fR, \fBINTENT(IN)\fR for \fBvdpowx\fR
.br
\h\'11\'\fBCOMPLEX\fR, \fBINTENT(IN)\fR for \fBvcpowx\fR
.br
\h\'11\'\fBDOUBLE COMPLEX\fR, \fBINTENT(IN)\fR for \fBvzpowx\fR
.br
\h\'2\'C:\h\'7\'\fBconst float*\fR for \fBvsPowx\fR
.br
\h\'11\'\fBconst double*\fR for \fBvdPowx\fR
.br
\h\'11\'\fBconst MKL\(ulComplex8*\fR for \fBvcPowx\fR
.br
\h\'11\'\fBconst MKL\(ulComplex16*\fR for \fBvzPowx\fR
.br
.SB Description
.br
\h\'2\'FORTRAN: Array \fIa\fR that specifies the input vector
.br
\h\'2\'C:\h\'7\'Pointer to an array that contains the input vector \fBa\fR.
.PP
.SB Name
\fBb\fR
.br
.SB Type
.br
\h\'2\'FORTRAN: \fBREAL\fR, \fBINTENT(IN)\fR for \fBvspowx\fR
.br
\h\'11\'\fBDOUBLE PRECISION\fR, \fBINTENT(IN)\fR for \fBvdpowx\fR
.br
\h\'11\'\fBCOMPLEX\fR, \fBINTENT(IN)\fR for \fBvcpowx\fR
.br
\h\'11\'\fBDOUBLE COMPLEX\fR, \fBINTENT(IN)\fR for \fBvzpowx\fR
.br
\h\'2\'C:\h\'7\'\fBconst float\fR for \fBvsPowx\fR
.br
\h\'11\'\fBconst double\fR for \fBvdPowx\fR
.br
\h\'11\'\fBconst MKL\(ulComplex8*\fR for \fBvcPowx\fR
.br
\h\'11\'\fBconst MKL\(ulComplex16*\fR for \fBvzPowx\fR
.br
.SB Description
.br
\h\'2\'FORTRAN: Scalar value \fIb\fR that is the constant power.
.br
\h\'2\'C:\h\'7\'Constant value for power \fBb\fR.
.PP
.B NOTE:
Overflow can occur also in \fBPowx\fR complex function, but the exact formula is beyond the scope of this document.
.SH OUTPUT PARAMETERS
.PP
.SB Name
.br
\h\'1\'\fBy\fR
.br
.SB Type
.br
\h\'2\'FORTRAN: \fBREAL\fR for \fBvspowx\fR
.br
\h\'11\'\fBDOUBLE PRECISION\fR for \fBvdpowx\fR
.br
\h\'11\'\fBCOMPLEX\fR for \fBvcpowx\fR
.br
\h\'11\'\fBDOUBLE COMPLEX\fR for \fBvzpowx\fR
.br
\h\'2\'C:\h\'7\'\fBfloat*\fR for \fBvsPowx\fR
.br
\h\'11\'\fBdouble*\fR for \fBvdPowx\fR
.br
\h\'11\'\fBMKL\(ulComplex8*\fR for \fBvcPowx\fR
.br
\h\'11\'\fBMKL\(ulComplex16*\fR for \fBvzPowx\fR
.br
.SB Description
.br
\h\'2\'FORTRAN: Array, specifies the output vector \fBy\fR.
.br
\h\'2\'C:\h\'7\'Pointer to an array that contains the output vector \fBy\fR.
