.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH second/dsecnd 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
second/dsecnd \- Returns elapsed CPU time in seconds.
.SH SYNOPSIS
.PP
\fIval\fR= \fBsecond()\fR
.PP
\fIval\fR= \fBdsecnd()\fR
.SH OUTPUT PARAMETERS

.TP 10
\fBval\fR
.NL
\fBREAL\fR for \fBsecond\fR
.IP
\fBDOUBLE PRECISION\fR for \fBdsecnd\fR
.IP
Elapsed CPU time in seconds.
