.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH setcpufrequency 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
setcpufrequency \- Sets CPU frequency value in GHz.
.SH SYNOPSIS
.PP
\fBsetcpufrequency\fR( \fIfreq\fR)
.SH OUTPUT PARAMETERS

.TP 10
\fBfreq\fR
.NL
\fBDOUBLE PRECISION\fR. CPU frequency value in GHz.
