.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH SetStart 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
SetStart \- Changes the value of the parameter \fIstart\fR in the convolution or correlation task descriptor.
.SH SYNOPSIS
.PP
.B ! Fortran
.PP
\fIstatus\fR= \fBvslconvsetstart\fR(\fItask\fR, \fIstart\fR)
.PP
\fIstatus\fR= \fBvslcorrsetstart\fR(\fItask\fR, \fIstart\fR)
.PP
.B /* C */
.PP
\fIstatus\fR= \fBvslConvSetStart\fR(\fItask\fR, \fIstart\fR);
.PP
\fIstatus\fR= \fBvslCorrSetStart\fR(\fItask\fR, \fIstart\fR);
.SH INPUT PARAMETERS
.PP
.SB Name
.br
\h\'1\'\fBtask\fR
.br
.SB Type
.br
\h\'2\'FORTRAN: \fBTYPE(VSL\(ulCONV\(ulTASK)\fR for \fBvslconvsetstart\fR
.br
\h\'11\'\fBTYPE(VSL\(ulCORR\(ulTASK)\fR for \fBvslcorrsetstart\fR
.br
\h\'2\'C:\h\'7\'\fBVSLConvTaskPtr\fR for \fBvslConvSetStart\fR
.br
\h\'11\'\fBVSLCorrTaskPtr\fR for \fBvslCorrSetStart\fR
.br
.SB Description
.br
\h\'1\'Pointer to the task descriptor.
.PP
.SB Name
.br
\h\'1\'\fBstart\fR
.br
.SB Type
.br
\h\'2\'FORTRAN: \fBINTEGER, DIMENSION (*)\fR
.br
\h\'2\'C:\h\'7\'\fBint[]\fR
.br
.SB Description
.br
\h\'1\'New value of the parameter \fIstart\fR.
.SH OUTPUT PARAMETERS
.PP
.SB Name
.br
\h\'1\'\fBstatus\fR
.br
.SB Type
.br
\h\'2\'FORTRAN: \fBINTEGER\fR
.br
\h\'2\'C:\h\'7\'\fBint\fR
.br
.SB Description
.br
\h\'1\'Current status of the task.
