.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH Sqr 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
Sqr \- 
.SH SYNOPSIS
.PP
.B ! Fortran
.PP
\fBcall vssqr\fR( \fIn\fR, \fIa\fR, \fIy\fR)
.PP
\fBcall vdsqr\fR( \fIn\fR, \fIa\fR, \fIy\fR)
.PP
.B /* C */
.PP
\fBvsSqr\fR( \fIn\fR, \fIa\fR, \fIy\fR);
.PP
\fBvdSqr\fR( \fIn\fR, \fIa\fR, \fIy\fR);
.SH INPUT PARAMETERS
.PP
.SB Name
.br
\h\'1\'\fBn\fR
.br
.SB Type
.br
\h\'2\'FORTRAN: \fBINTEGER\fR, \fBINTENT(IN)\fR
.br
\h\'2\'C:\h\'7\'\fBint\fR
.br
.SB Description
.br
\h\'1\'Specifies the number of elements to be calculated.
.PP
.SB Name
.br
\h\'1\'\fBa\fR
.br
.SB Type
.br
\h\'2\'FORTRAN: \fBREAL\fR, \fBINTENT(IN)\fR for \fBvssqr\fR
.br
\h\'11\'\fBDOUBLE PRECISION\fR, \fBINTENT(IN)\fR for \fBvdsqr\fR
.br
\h\'2\'C:\h\'7\'\fBconst float*\fR for \fBvsSqr\fR
.br
\h\'11\'\fBconst double*\fR for \fBvdSqr\fR
.br
.SB Description
.br
\h\'2\'FORTRAN: Array, specifies the input vector \fBa\fR.
.br
\h\'2\'C:\h\'7\'Pointer to an array that contains the input vector \fBa\fR.
.SH OUTPUT PARAMETERS
.PP
.SB Name
.br
\h\'1\'\fBy\fR
.br
.SB Type
.br
\h\'2\'FORTRAN: \fBREAL\fR for \fBvssqr\fR
.br
\h\'11\'\fBDOUBLE PRECISION\fR for \fBvdsqr\fR
.br
\h\'2\'C:\h\'7\'\fBfloat*\fR for \fBvsSqr\fR
.br
\h\'11\'\fBdouble*\fR for \fBvdSqr\fR
.br
.SB Description
.br
\h\'2\'FORTRAN: Array, specifies the output vector \fBy\fR.
.br
\h\'2\'C:\h\'7\'Pointer to an array that contains the output vector \fBy\fR.
