.\" Copyright (c) 2002 \- 2008 Intel Corporation
.\" All rights reserved.
.\"
.TH ?symm 3 "Intel Corporation" "Copyright(C) 2002 \- 2008" "Intel(R) Math Kernel Library"
.SH NAME
?symm \- Performs a scalar-matrix-matrix product(one matrix operand is symmetric) and adds the result to a scalar-matrix product.
.SH SYNOPSIS
.PP
.B Fortran 77
.PP
\fBcall ssymm\fR(\fIside\fR, \fIuplo\fR, \fIm\fR, \fIn\fR, \fIalpha\fR, \fIa\fR, \fIlda\fR, \fIb\fR, \fIldb\fR, \fIbeta\fR, \fIc\fR, \fIldc\fR)
.PP
\fBcall dsymm\fR(\fIside\fR, \fIuplo\fR, \fIm\fR, \fIn\fR, \fIalpha\fR, \fIa\fR, \fIlda\fR, \fIb\fR, \fIldb\fR, \fIbeta\fR, \fIc\fR, \fIldc\fR)
.PP
\fBcall csymm\fR(\fIside\fR, \fIuplo\fR, \fIm\fR, \fIn\fR, \fIalpha\fR, \fIa\fR, \fIlda\fR, \fIb\fR, \fIldb\fR, \fIbeta\fR, \fIc\fR, \fIldc\fR)
.PP
\fBcall zsymm\fR(\fIside\fR, \fIuplo\fR, \fIm\fR, \fIn\fR, \fIalpha\fR, \fIa\fR, \fIlda\fR, \fIb\fR, \fIldb\fR, \fIbeta\fR, \fIc\fR, \fIldc\fR)
.PP
.B Fortran 95
.PP
\fBcall symm\fR(\fIa\fR, \fIb\fR, \fIc\fR[,\fIside\fR][,\fIuplo\fR] [,\fIalpha\fR][,\fIbeta\fR])
.SH INPUT PARAMETERS

.TP 10
\fBside\fR
.NL
\fBCHARACTER*1\fR. Specifies whether the symmetric matrix \fIA\fR appears on the left or right in the operation:
.IP
if \fIside\fR = \fB\'L\'\fR or \fB\'l\'\fR, then \fIC\fR := \fIalpha\fR*\fIA\fR*\fIB\fR + \fIbeta\fR*\fIC\fR;
.IP
if \fIside\fR = \fB\'R\'\fR or \fB\'r\'\fR, then \fIC\fR := \fIalpha\fR*\fIB\fR*\fIA\fR + \fIbeta\fR*\fIC\fR.
.TP 10
\fBuplo\fR
.NL
\fBCHARACTER*1\fR. Specifies whether the upper or lower triangular part of the symmetric matrix \fIA\fR is used:
.IP
if \fIuplo\fR = \fB\'U\'\fR or \fB\'u\'\fR, then the upper triangular part is used;
.IP
if \fIuplo\fR = \fB\'L\'\fR or \fB\'l\'\fR,  then the lower triangular part is used.
.TP 10
\fBm\fR
.NL
\fBINTEGER\fR. Specifies the number of rows of the matrix \fIC\fR.
.IP
The value of \fIm\fR must be at least zero.
.TP 10
\fBn\fR
.NL
\fBINTEGER\fR. Specifies the number of columns of the matrix \fIC\fR.
.IP
The value of \fIn\fR must be at least zero.
.TP 10
\fBalpha\fR
.NL
\fBREAL\fR for \fBssymm\fR
.IP
\fBDOUBLE PRECISION\fR for \fBdsymm\fR
.IP
\fBCOMPLEX\fR for \fBcsymm\fR
.IP
\fBDOUBLE COMPLEX\fR for \fBzsymm\fR
.IP
Specifies the scalar \fIalpha\fR.
.TP 10
\fBa\fR
.NL
\fBREAL\fR for \fBssymm\fR
.IP
\fBDOUBLE PRECISION\fR for \fBdsymm\fR
.IP
\fBCOMPLEX\fR for \fBcsymm\fR
.IP
\fBDOUBLE COMPLEX\fR for \fBzsymm\fR
.IP
Array, \fBDIMENSION\fR(\fIlda\fR, \fIka\fR), where \fIka\fR is \fIm\fR when \fIside\fR = \fB\'L\'\fR or \fB\'l\'\fR and is \fIn\fR otherwise.
.IP
Before entry with \fIside\fR = \fB\'L\'\fR or \fB\'l\'\fR, the \fIm\fR-by-\fIm\fR part of the array \fIa\fR must contain the symmetric matrix, such that when \fIuplo\fR = \fB\'U\'\fR or \fB\'u\'\fR, the leading \fIm\fR-by-\fIm\fR upper triangular part of the array \fIa\fR must contain the upper triangular part of the symmetric matrix and the strictly lower triangular part of \fIa\fR is not referenced, and when \fIuplo\fR = \fB\'L\'\fR or \fB\'l\'\fR, the leading \fIm\fR-by-\fIm\fR lower triangular part of the array \fIa\fR must contain the lower triangular part of the symmetric matrix and the strictly upper triangular part of \fIa\fR is not referenced.
.IP
Before entry with \fIside\fR = \fB\'R\'\fR or \fB\'r\'\fR, the \fIn\fR-by-\fIn\fR part of the array \fIa\fR must contain the symmetric matrix, such that when \fIuplo\fR = \fB\'U\'\fR or \fB\'u\'\fR, the leading \fIn\fR-by-\fIn\fR upper triangular part of the array \fIa\fR must contain the upper triangular part of the symmetric matrix and the strictly lower triangular part of \fIa\fR is not referenced, and when \fIuplo\fR = \fB\'L\'\fR or \fB\'l\'\fR, the leading \fIn\fR-by-\fIn\fR lower triangular part of the array \fIa\fR must contain the lower triangular part of the symmetric matrix and the strictly upper triangular part of \fIa\fR is not referenced.
.TP 10
\fBlda\fR
.NL
\fBINTEGER\fR. Specifies the first dimension of \fIa\fR as declared in the calling (sub)program. When \fIside\fR = \fB\'L\'\fR or \fB\'l\'\fR then \fIlda\fR must be at least max(1, \fIm\fR), otherwise \fIlda\fR must be at least max(1, \fIn\fR).
.TP 10
\fBb\fR
.NL
\fBREAL\fR for \fBssymm\fR
.IP
\fBDOUBLE PRECISION\fR for \fBdsymm\fR
.IP
\fBCOMPLEX\fR for \fBcsymm\fR
.IP
\fBDOUBLE COMPLEX\fR for \fBzsymm\fR
.IP
Array, \fBDIMENSION\fR(\fIldb\fR,\fIn\fR). Before entry, the leading \fIm\fR-by-\fIn\fR part of the array \fBb\fR must contain the matrix \fIB\fR.
.TP 10
\fBldb\fR
.NL
\fBINTEGER\fR. Specifies the first dimension of \fBb\fR as declared in the calling (sub)program. The value of \fIldb\fR must be at least max(1, \fIm\fR).
.TP 10
\fBbeta\fR
.NL
\fBREAL\fR for \fBssymm\fR
.IP
\fBDOUBLE PRECISION\fR for \fBdsymm\fR
.IP
\fBCOMPLEX\fR for \fBcsymm\fR
.IP
\fBDOUBLE COMPLEX\fR for \fBzsymm\fR
.IP
Specifies the scalar \fIbeta\fR.
.IP
When \fIbeta\fR is set to zero, then \fIc\fR need not be set on input.
.TP 10
\fBc\fR
.NL
\fBREAL\fR for \fBssymm\fR
.IP
\fBDOUBLE PRECISION\fR for \fBdsymm\fR
.IP
\fBCOMPLEX\fR for \fBcsymm\fR
.IP
\fBDOUBLE COMPLEX\fR for \fBzsymm\fR
.IP
Array, \fBDIMENSION\fR (\fIldc\fR,\fIn\fR). Before entry, the leading \fIm\fR-by-\fIn\fR part of the array \fIc\fR must contain the matrix \fIC\fR, except when beta is zero, in which case \fIc\fR need not be set on entry.
.TP 10
\fBldc\fR
.NL
\fBINTEGER\fR. Specifies the first dimension of \fIc\fR as declared in the calling (sub)program. The value of \fIldc\fR must be at least max(1, \fIm\fR).
.SH OUTPUT PARAMETERS

.TP 10
\fBc\fR
.NL
Overwritten by the \fIm\fR-by-\fIn\fR updated matrix.
.SH FORTRAN 95 INTERFACE NOTES
.PP
.PP
Routines in Fortran 95 interface have fewer arguments in the calling sequence than their Fortran 77   counterparts. For general conventions applied to skip redundant or reconstructible arguments, see Fortran 95 Interface Conventions.
.PP
Specific details for the routine \fBsymm\fR interface are the following:
.TP 10
\fBa\fR
.NL
Holds the matrix \fIA\fR of size (\fIk\fR,\fIk\fR) where 
.IP
\fIk\fR = \fIm\fR if \fIside\fR = \fB\'L\'\fR, 
.IP
\fIk\fR = \fIn\fR otherwise.
.TP 10
\fBb\fR
.NL
Holds the matrix \fIB\fR of size (\fIm\fR,\fIn\fR).
.TP 10
\fBc\fR
.NL
Holds the matrix \fIC\fR of size (\fIm\fR,\fIn\fR).
.TP 10
\fBside\fR
.NL
Must be \fB\'L\'\fR or \fB\'R\'\fR. The default value is \fB\'L\'\fR.
.TP 10
\fBuplo\fR
.NL
Must be \fB\'U\'\fR or \fB\'L\'\fR. The default value is \fB\'U\'\fR.
.TP 10
\fBalpha\fR
.NL
The default value is 1.
.TP 10
\fBbeta\fR
.NL
The default value is 1.
