!*******************************************************************************
!                              INTEL CONFIDENTIAL
!   Copyright(C) 2005-2008 Intel Corporation. All Rights Reserved.
!   The source code contained  or  described herein and all documents related to
!   the source code ("Material") are owned by Intel Corporation or its suppliers
!   or licensors.  Title to the  Material remains with  Intel Corporation or its
!   suppliers and licensors. The Material contains trade secrets and proprietary
!   and  confidential  information of  Intel or its suppliers and licensors. The
!   Material  is  protected  by  worldwide  copyright  and trade secret laws and
!   treaty  provisions. No part of the Material may be used, copied, reproduced,
!   modified, published, uploaded, posted, transmitted, distributed or disclosed
!   in any way without Intel's prior express written permission.
!   No license  under any  patent, copyright, trade secret or other intellectual
!   property right is granted to or conferred upon you by disclosure or delivery
!   of the Materials,  either expressly, by implication, inducement, estoppel or
!   otherwise.  Any  license  under  such  intellectual property  rights must be
!   express and approved by Intel in writing.
!
!*******************************************************************************
!  Content:
!       MKL BLAS77 interface as prototypes for MKL BLAS95 interfaces
!
!*******************************************************************************


MODULE MKL77_BLAS

! BLAS level 1
INTERFACE MKL77_ASUM
  PURE FUNCTION SASUM(N,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP) :: SASUM
    REAL(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END FUNCTION SASUM
  PURE FUNCTION SCASUM(N,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP) :: SCASUM
    COMPLEX(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END FUNCTION SCASUM
  PURE FUNCTION DASUM(N,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP) :: DASUM
    REAL(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END FUNCTION DASUM
  PURE FUNCTION DZASUM(N,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP) :: DZASUM
    COMPLEX(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END FUNCTION DZASUM
END INTERFACE MKL77_ASUM

INTERFACE MKL77_AXPY
  PURE SUBROUTINE SAXPY(N,A,X,INCX,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(IN) :: X(*)
    REAL(WP), INTENT(INOUT) :: Y(*)
    REAL(WP), INTENT(IN) :: A
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE SAXPY
  PURE SUBROUTINE DAXPY(N,A,X,INCX,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(IN) :: X(*)
    REAL(WP), INTENT(INOUT) :: Y(*)
    REAL(WP), INTENT(IN) :: A
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE DAXPY
  PURE SUBROUTINE CAXPY(N,A,X,INCX,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(INOUT) :: Y(*)
    COMPLEX(WP), INTENT(IN) :: A
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE CAXPY
  PURE SUBROUTINE ZAXPY(N,A,X,INCX,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(INOUT) :: Y(*)
    COMPLEX(WP), INTENT(IN) :: A
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE ZAXPY
END INTERFACE MKL77_AXPY

INTERFACE MKL77_COPY
  PURE SUBROUTINE SCOPY(N,X,INCX,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(IN) :: X(*)
    REAL(WP), INTENT(INOUT) :: Y(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE SCOPY
  PURE SUBROUTINE DCOPY(N,X,INCX,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(IN) :: X(*)
    REAL(WP), INTENT(INOUT) :: Y(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE DCOPY
  PURE SUBROUTINE CCOPY(N,X,INCX,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(INOUT) :: Y(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE CCOPY
  PURE SUBROUTINE ZCOPY(N,X,INCX,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(INOUT) :: Y(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE ZCOPY
END INTERFACE MKL77_COPY

INTERFACE MKL77_DOT
  PURE FUNCTION SDOT(N,X,INCX,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP) :: SDOT
    REAL(WP), INTENT(IN) :: X(*)
    REAL(WP), INTENT(IN) :: Y(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END FUNCTION SDOT
  PURE FUNCTION DDOT(N,X,INCX,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP) :: DDOT
    REAL(WP), INTENT(IN) :: X(*)
    REAL(WP), INTENT(IN) :: Y(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END FUNCTION DDOT
END INTERFACE MKL77_DOT

INTERFACE MKL77_SDOT
  PURE FUNCTION SDSDOT(N,SB,SX,INCX,SY,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP) :: SDSDOT
    REAL(WP), INTENT(IN) :: SX(*)
    REAL(WP), INTENT(IN) :: SY(*)
    REAL(WP), INTENT(IN) :: SB
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END FUNCTION SDSDOT
  PURE FUNCTION DSDOT(N,SX,INCX,SY,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    INTEGER, PARAMETER :: SP = KIND(1.0E0)
    REAL(WP) :: DSDOT
    REAL(SP), INTENT(IN) :: SX(*)
    REAL(SP), INTENT(IN) :: SY(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END FUNCTION DSDOT
END INTERFACE MKL77_SDOT

INTERFACE MKL77_DOTC
  PURE FUNCTION CDOTC(N,X,INCX,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP) :: CDOTC
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(IN) :: Y(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END FUNCTION CDOTC
  PURE FUNCTION ZDOTC(N,X,INCX,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP) :: ZDOTC
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(IN) :: Y(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END FUNCTION ZDOTC
END INTERFACE MKL77_DOTC

INTERFACE MKL77_DOTU
  PURE FUNCTION CDOTU(N,X,INCX,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP) :: CDOTU
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(IN) :: Y(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END FUNCTION CDOTU
  PURE FUNCTION ZDOTU(N,X,INCX,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP) :: ZDOTU
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(IN) :: Y(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END FUNCTION ZDOTU
END INTERFACE MKL77_DOTU

INTERFACE MKL77_NRM2
  PURE FUNCTION SNRM2(N,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP) :: SNRM2
    REAL(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END FUNCTION SNRM2
  PURE FUNCTION DNRM2(N,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP) :: DNRM2
    REAL(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END FUNCTION DNRM2
  PURE FUNCTION SCNRM2(N,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP) :: SCNRM2
    COMPLEX(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END FUNCTION SCNRM2
  PURE FUNCTION DZNRM2(N,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP) :: DZNRM2
    COMPLEX(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END FUNCTION DZNRM2
END INTERFACE MKL77_NRM2

INTERFACE MKL77_ROT
  PURE SUBROUTINE SROT(N,X,INCX,Y,INCY,C,S)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(INOUT) :: X(*)
    REAL(WP), INTENT(INOUT) :: Y(*)
    REAL(WP), INTENT(IN) :: C
    REAL(WP), INTENT(IN) :: S
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE SROT
  PURE SUBROUTINE DROT(N,X,INCX,Y,INCY,C,S)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(INOUT) :: X(*)
    REAL(WP), INTENT(INOUT) :: Y(*)
    REAL(WP), INTENT(IN) :: C
    REAL(WP), INTENT(IN) :: S
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE DROT
  PURE SUBROUTINE CSROT(N,X,INCX,Y,INCY,C,S)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(INOUT) :: X(*)
    COMPLEX(WP), INTENT(INOUT) :: Y(*)
    REAL(WP), INTENT(IN) :: C
    REAL(WP), INTENT(IN) :: S
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE CSROT
  PURE SUBROUTINE ZDROT(N,X,INCX,Y,INCY,C,S)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(INOUT) :: X(*)
    COMPLEX(WP), INTENT(INOUT) :: Y(*)
    REAL(WP), INTENT(IN) :: C
    REAL(WP), INTENT(IN) :: S
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE ZDROT
END INTERFACE MKL77_ROT

INTERFACE MKL77_ROTG
  PURE SUBROUTINE SROTG(A,B,C,S)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(INOUT) :: A
    REAL(WP), INTENT(INOUT) :: B
    REAL(WP), INTENT(OUT) :: C
    REAL(WP), INTENT(OUT) :: S
  END SUBROUTINE SROTG
  PURE SUBROUTINE DROTG(A,B,C,S)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(INOUT) :: A
    REAL(WP), INTENT(INOUT) :: B
    REAL(WP), INTENT(OUT) :: C
    REAL(WP), INTENT(OUT) :: S
  END SUBROUTINE DROTG
  PURE SUBROUTINE CROTG(A,B,C,S)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(INOUT) :: A
    COMPLEX(WP), INTENT(INOUT) :: B
    REAL(WP), INTENT(OUT) :: C
    COMPLEX(WP), INTENT(OUT) :: S
  END SUBROUTINE CROTG
  PURE SUBROUTINE ZROTG(A,B,C,S)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(INOUT) :: A
    COMPLEX(WP), INTENT(INOUT) :: B
    REAL(WP), INTENT(OUT) :: C
    COMPLEX(WP), INTENT(OUT) :: S
  END SUBROUTINE ZROTG
END INTERFACE MKL77_ROTG

INTERFACE MKL77_ROTM
  PURE SUBROUTINE SROTM(N,X,INCX,Y,INCY,PARAM)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(INOUT) :: X(*)
    REAL(WP), INTENT(INOUT) :: Y(*)
    REAL(WP), INTENT(IN) :: PARAM(5)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE SROTM
  PURE SUBROUTINE DROTM(N,X,INCX,Y,INCY,PARAM)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(INOUT) :: X(*)
    REAL(WP), INTENT(INOUT) :: Y(*)
    REAL(WP), INTENT(IN) :: PARAM(5)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE DROTM
END INTERFACE MKL77_ROTM

INTERFACE MKL77_ROTMG
  PURE SUBROUTINE SROTMG(D1,D2,X1,Y1,PARAM)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(INOUT) :: X1
    REAL(WP), INTENT(IN) :: Y1
    REAL(WP), INTENT(OUT) :: PARAM(5)
    REAL(WP), INTENT(INOUT) :: D1
    REAL(WP), INTENT(INOUT) :: D2
  END SUBROUTINE SROTMG
  PURE SUBROUTINE DROTMG(D1,D2,X1,Y1,PARAM)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(INOUT) :: X1
    REAL(WP), INTENT(IN) :: Y1
    REAL(WP), INTENT(OUT) :: PARAM(5)
    REAL(WP), INTENT(INOUT) :: D1
    REAL(WP), INTENT(INOUT) :: D2
  END SUBROUTINE DROTMG
END INTERFACE MKL77_ROTMG

INTERFACE MKL77_SCAL
  PURE SUBROUTINE SSCAL(N,A,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(INOUT) :: X(*)
    REAL(WP), INTENT(IN) :: A
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE SSCAL
  PURE SUBROUTINE DSCAL(N,A,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(INOUT) :: X(*)
    REAL(WP), INTENT(IN) :: A
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE DSCAL
  PURE SUBROUTINE CSCAL(N,A,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(INOUT) :: X(*)
    COMPLEX(WP), INTENT(IN) :: A
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE CSCAL
  PURE SUBROUTINE ZSCAL(N,A,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(INOUT) :: X(*)
    COMPLEX(WP), INTENT(IN) :: A
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE ZSCAL
  PURE SUBROUTINE CSSCAL(N,A,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(INOUT) :: X(*)
    REAL(WP), INTENT(IN) :: A
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE CSSCAL
  PURE SUBROUTINE ZDSCAL(N,A,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(INOUT) :: X(*)
    REAL(WP), INTENT(IN) :: A
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE ZDSCAL
END INTERFACE MKL77_SCAL

INTERFACE MKL77_SWAP
  PURE SUBROUTINE SSWAP(N,X,INCX,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(INOUT) :: X(*)
    REAL(WP), INTENT(INOUT) :: Y(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE SSWAP
  PURE SUBROUTINE DSWAP(N,X,INCX,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(INOUT) :: X(*)
    REAL(WP), INTENT(INOUT) :: Y(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE DSWAP
  PURE SUBROUTINE CSWAP(N,X,INCX,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(INOUT) :: X(*)
    COMPLEX(WP), INTENT(INOUT) :: Y(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE CSWAP
  PURE SUBROUTINE ZSWAP(N,X,INCX,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(INOUT) :: X(*)
    COMPLEX(WP), INTENT(INOUT) :: Y(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE ZSWAP
END INTERFACE MKL77_SWAP

INTERFACE MKL77_IAMAX
  PURE FUNCTION ISAMAX(N,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    INTEGER :: ISAMAX
    REAL(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END FUNCTION ISAMAX
  PURE FUNCTION IDAMAX(N,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    INTEGER :: IDAMAX
    REAL(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END FUNCTION IDAMAX
  PURE FUNCTION ICAMAX(N,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    INTEGER :: ICAMAX
    COMPLEX(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END FUNCTION ICAMAX
  PURE FUNCTION IZAMAX(N,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    INTEGER :: IZAMAX
    COMPLEX(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END FUNCTION IZAMAX
END INTERFACE MKL77_IAMAX

INTERFACE MKL77_IAMIN
  PURE FUNCTION ISAMIN(N,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    INTEGER :: ISAMIN
    REAL(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END FUNCTION ISAMIN
  PURE FUNCTION IDAMIN(N,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    INTEGER :: IDAMIN
    REAL(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END FUNCTION IDAMIN
  PURE FUNCTION ICAMIN(N,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    INTEGER :: ICAMIN
    COMPLEX(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END FUNCTION ICAMIN
  PURE FUNCTION IZAMIN(N,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    INTEGER :: IZAMIN
    COMPLEX(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END FUNCTION IZAMIN
END INTERFACE MKL77_IAMIN

INTERFACE MKL77_DCABS1
  PURE FUNCTION DCABS1(Z)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP) :: DCABS1
    COMPLEX(WP), INTENT(IN) :: Z
  END FUNCTION DCABS1
END INTERFACE MKL77_DCABS1

INTERFACE MKL77_GBMV
  PURE SUBROUTINE SGBMV(TRANS,M,N,KL,KU,ALPHA,A,LDA,X,INCX,BETA,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(IN) :: X(*)
    REAL(WP), INTENT(INOUT) :: Y(*)
    INTEGER, INTENT(IN) :: KL
    INTEGER, INTENT(IN) :: M
    REAL(WP), INTENT(IN) :: ALPHA
    REAL(WP), INTENT(IN) :: BETA
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: KU
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE SGBMV
  PURE SUBROUTINE DGBMV(TRANS,M,N,KL,KU,ALPHA,A,LDA,X,INCX,BETA,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(IN) :: X(*)
    REAL(WP), INTENT(INOUT) :: Y(*)
    INTEGER, INTENT(IN) :: KL
    INTEGER, INTENT(IN) :: M
    REAL(WP), INTENT(IN) :: ALPHA
    REAL(WP), INTENT(IN) :: BETA
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: KU
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE DGBMV
  PURE SUBROUTINE CGBMV(TRANS,M,N,KL,KU,ALPHA,A,LDA,X,INCX,BETA,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(INOUT) :: Y(*)
    INTEGER, INTENT(IN) :: KL
    INTEGER, INTENT(IN) :: M
    COMPLEX(WP), INTENT(IN) :: ALPHA
    COMPLEX(WP), INTENT(IN) :: BETA
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: KU
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE CGBMV
  PURE SUBROUTINE ZGBMV(TRANS,M,N,KL,KU,ALPHA,A,LDA,X,INCX,BETA,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(INOUT) :: Y(*)
    INTEGER, INTENT(IN) :: KL
    INTEGER, INTENT(IN) :: M
    COMPLEX(WP), INTENT(IN) :: ALPHA
    COMPLEX(WP), INTENT(IN) :: BETA
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: KU
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE ZGBMV
END INTERFACE MKL77_GBMV

INTERFACE MKL77_GEMV
  PURE SUBROUTINE SGEMV(TRANS,M,N,ALPHA,A,LDA,X,INCX,BETA,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(IN) :: X(*)
    REAL(WP), INTENT(INOUT) :: Y(*)
    REAL(WP), INTENT(IN) :: ALPHA
    REAL(WP), INTENT(IN) :: BETA
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE SGEMV
  PURE SUBROUTINE DGEMV(TRANS,M,N,ALPHA,A,LDA,X,INCX,BETA,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(IN) :: X(*)
    REAL(WP), INTENT(INOUT) :: Y(*)
    REAL(WP), INTENT(IN) :: ALPHA
    REAL(WP), INTENT(IN) :: BETA
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE DGEMV
  PURE SUBROUTINE CGEMV(TRANS,M,N,ALPHA,A,LDA,X,INCX,BETA,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(INOUT) :: Y(*)
    COMPLEX(WP), INTENT(IN) :: ALPHA
    COMPLEX(WP), INTENT(IN) :: BETA
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE CGEMV
  PURE SUBROUTINE ZGEMV(TRANS,M,N,ALPHA,A,LDA,X,INCX,BETA,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(INOUT) :: Y(*)
    COMPLEX(WP), INTENT(IN) :: ALPHA
    COMPLEX(WP), INTENT(IN) :: BETA
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE ZGEMV
END INTERFACE MKL77_GEMV

INTERFACE MKL77_GER
  PURE SUBROUTINE SGER(M,N,ALPHA,X,INCX,Y,INCY,A,LDA)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(INOUT) :: A(LDA,*)
    REAL(WP), INTENT(IN) :: X(*)
    REAL(WP), INTENT(IN) :: Y(*)
    REAL(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE SGER
  PURE SUBROUTINE DGER(M,N,ALPHA,X,INCX,Y,INCY,A,LDA)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(INOUT) :: A(LDA,*)
    REAL(WP), INTENT(IN) :: X(*)
    REAL(WP), INTENT(IN) :: Y(*)
    REAL(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE DGER
END INTERFACE MKL77_GER

INTERFACE MKL77_GERC
  PURE SUBROUTINE CGERC(M,N,ALPHA,X,INCX,Y,INCY,A,LDA)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(INOUT) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(IN) :: Y(*)
    COMPLEX(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE CGERC
  PURE SUBROUTINE ZGERC(M,N,ALPHA,X,INCX,Y,INCY,A,LDA)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(INOUT) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(IN) :: Y(*)
    COMPLEX(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE ZGERC
END INTERFACE MKL77_GERC

INTERFACE MKL77_GERU
  PURE SUBROUTINE CGERU(M,N,ALPHA,X,INCX,Y,INCY,A,LDA)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(INOUT) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(IN) :: Y(*)
    COMPLEX(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE CGERU
  PURE SUBROUTINE ZGERU(M,N,ALPHA,X,INCX,Y,INCY,A,LDA)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(INOUT) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(IN) :: Y(*)
    COMPLEX(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE ZGERU
END INTERFACE MKL77_GERU

INTERFACE MKL77_HBMV
  PURE SUBROUTINE CHBMV(UPLO,N,K,ALPHA,A,LDA,X,INCX,BETA,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(INOUT) :: Y(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    COMPLEX(WP), INTENT(IN) :: ALPHA
    COMPLEX(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE CHBMV
  PURE SUBROUTINE ZHBMV(UPLO,N,K,ALPHA,A,LDA,X,INCX,BETA,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(INOUT) :: Y(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    COMPLEX(WP), INTENT(IN) :: ALPHA
    COMPLEX(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE ZHBMV
END INTERFACE MKL77_HBMV

INTERFACE MKL77_HEMV
  PURE SUBROUTINE CHEMV(UPLO,N,ALPHA,A,LDA,X,INCX,BETA,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(INOUT) :: Y(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    COMPLEX(WP), INTENT(IN) :: ALPHA
    COMPLEX(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE CHEMV
  PURE SUBROUTINE ZHEMV(UPLO,N,ALPHA,A,LDA,X,INCX,BETA,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(INOUT) :: Y(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    COMPLEX(WP), INTENT(IN) :: ALPHA
    COMPLEX(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE ZHEMV
END INTERFACE MKL77_HEMV

INTERFACE MKL77_HER
  PURE SUBROUTINE CHER(UPLO,N,ALPHA,X,INCX,A,LDA)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(INOUT) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    REAL(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE CHER
  PURE SUBROUTINE ZHER(UPLO,N,ALPHA,X,INCX,A,LDA)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(INOUT) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    REAL(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE ZHER
END INTERFACE MKL77_HER

INTERFACE MKL77_HER2
  PURE SUBROUTINE CHER2(UPLO,N,ALPHA,X,INCX,Y,INCY,A,LDA)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(INOUT) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(IN) :: Y(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    COMPLEX(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE CHER2
  PURE SUBROUTINE ZHER2(UPLO,N,ALPHA,X,INCX,Y,INCY,A,LDA)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(INOUT) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(IN) :: Y(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    COMPLEX(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE ZHER2
END INTERFACE MKL77_HER2

INTERFACE MKL77_HPMV
  PURE SUBROUTINE CHPMV(UPLO,N,ALPHA,A,X,INCX,BETA,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(IN) :: A(*)
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(INOUT) :: Y(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    COMPLEX(WP), INTENT(IN) :: ALPHA
    COMPLEX(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE CHPMV
  PURE SUBROUTINE ZHPMV(UPLO,N,ALPHA,A,X,INCX,BETA,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(IN) :: A(*)
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(INOUT) :: Y(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    COMPLEX(WP), INTENT(IN) :: ALPHA
    COMPLEX(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE ZHPMV
END INTERFACE MKL77_HPMV

INTERFACE MKL77_HPR
  PURE SUBROUTINE CHPR(UPLO,N,ALPHA,X,INCX,A)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(INOUT) :: A(*)
    COMPLEX(WP), INTENT(IN) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    REAL(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE CHPR
  PURE SUBROUTINE ZHPR(UPLO,N,ALPHA,X,INCX,A)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(INOUT) :: A(*)
    COMPLEX(WP), INTENT(IN) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    REAL(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE ZHPR
END INTERFACE MKL77_HPR

INTERFACE MKL77_HPR2
  PURE SUBROUTINE CHPR2(UPLO,N,ALPHA,X,INCX,Y,INCY,A)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(INOUT) :: A(*)
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(IN) :: Y(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    COMPLEX(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE CHPR2
  PURE SUBROUTINE ZHPR2(UPLO,N,ALPHA,X,INCX,Y,INCY,A)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(INOUT) :: A(*)
    COMPLEX(WP), INTENT(IN) :: X(*)
    COMPLEX(WP), INTENT(IN) :: Y(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    COMPLEX(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE ZHPR2
END INTERFACE MKL77_HPR2

INTERFACE MKL77_SBMV
  PURE SUBROUTINE SSBMV(UPLO,N,K,ALPHA,A,LDA,X,INCX,BETA,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(IN) :: X(*)
    REAL(WP), INTENT(INOUT) :: Y(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    REAL(WP), INTENT(IN) :: ALPHA
    REAL(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE SSBMV
  PURE SUBROUTINE DSBMV(UPLO,N,K,ALPHA,A,LDA,X,INCX,BETA,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(IN) :: X(*)
    REAL(WP), INTENT(INOUT) :: Y(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    REAL(WP), INTENT(IN) :: ALPHA
    REAL(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE DSBMV
END INTERFACE MKL77_SBMV

INTERFACE MKL77_SPMV
  PURE SUBROUTINE SSPMV(UPLO,N,ALPHA,A,X,INCX,BETA,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(IN) :: A(*)
    REAL(WP), INTENT(IN) :: X(*)
    REAL(WP), INTENT(INOUT) :: Y(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    REAL(WP), INTENT(IN) :: ALPHA
    REAL(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE SSPMV
  PURE SUBROUTINE DSPMV(UPLO,N,ALPHA,A,X,INCX,BETA,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(IN) :: A(*)
    REAL(WP), INTENT(IN) :: X(*)
    REAL(WP), INTENT(INOUT) :: Y(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    REAL(WP), INTENT(IN) :: ALPHA
    REAL(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE DSPMV
END INTERFACE MKL77_SPMV

INTERFACE MKL77_SPR
  PURE SUBROUTINE SSPR(UPLO,N,ALPHA,X,INCX,A)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(INOUT) :: A(*)
    REAL(WP), INTENT(IN) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    REAL(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE SSPR
  PURE SUBROUTINE DSPR(UPLO,N,ALPHA,X,INCX,A)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(INOUT) :: A(*)
    REAL(WP), INTENT(IN) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    REAL(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE DSPR
END INTERFACE MKL77_SPR

INTERFACE MKL77_SPR2
  PURE SUBROUTINE SSPR2(UPLO,N,ALPHA,X,INCX,Y,INCY,A)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(INOUT) :: A(*)
    REAL(WP), INTENT(IN) :: X(*)
    REAL(WP), INTENT(IN) :: Y(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    REAL(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE SSPR2
  PURE SUBROUTINE DSPR2(UPLO,N,ALPHA,X,INCX,Y,INCY,A)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(INOUT) :: A(*)
    REAL(WP), INTENT(IN) :: X(*)
    REAL(WP), INTENT(IN) :: Y(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    REAL(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE DSPR2
END INTERFACE MKL77_SPR2

INTERFACE MKL77_SYMV
  PURE SUBROUTINE SSYMV(UPLO,N,ALPHA,A,LDA,X,INCX,BETA,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(IN) :: X(*)
    REAL(WP), INTENT(INOUT) :: Y(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    REAL(WP), INTENT(IN) :: ALPHA
    REAL(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE SSYMV
  PURE SUBROUTINE DSYMV(UPLO,N,ALPHA,A,LDA,X,INCX,BETA,Y,INCY)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(IN) :: X(*)
    REAL(WP), INTENT(INOUT) :: Y(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    REAL(WP), INTENT(IN) :: ALPHA
    REAL(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE DSYMV
END INTERFACE MKL77_SYMV

INTERFACE MKL77_SYR
  PURE SUBROUTINE SSYR(UPLO,N,ALPHA,X,INCX,A,LDA)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(INOUT) :: A(LDA,*)
    REAL(WP), INTENT(IN) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    REAL(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE SSYR
  PURE SUBROUTINE DSYR(UPLO,N,ALPHA,X,INCX,A,LDA)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(INOUT) :: A(LDA,*)
    REAL(WP), INTENT(IN) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    REAL(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE DSYR
END INTERFACE MKL77_SYR

INTERFACE MKL77_SYR2
  PURE SUBROUTINE SSYR2(UPLO,N,ALPHA,X,INCX,Y,INCY,A,LDA)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(INOUT) :: A(LDA,*)
    REAL(WP), INTENT(IN) :: X(*)
    REAL(WP), INTENT(IN) :: Y(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    REAL(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE SSYR2
  PURE SUBROUTINE DSYR2(UPLO,N,ALPHA,X,INCX,Y,INCY,A,LDA)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(INOUT) :: A(LDA,*)
    REAL(WP), INTENT(IN) :: X(*)
    REAL(WP), INTENT(IN) :: Y(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    REAL(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: INCY
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE DSYR2
END INTERFACE MKL77_SYR2

INTERFACE MKL77_TBMV
  PURE SUBROUTINE STBMV(UPLO,TRANS,DIAG,N,K,A,LDA,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(INOUT) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE STBMV
  PURE SUBROUTINE DTBMV(UPLO,TRANS,DIAG,N,K,A,LDA,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(INOUT) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE DTBMV
  PURE SUBROUTINE CTBMV(UPLO,TRANS,DIAG,N,K,A,LDA,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(INOUT) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE CTBMV
  PURE SUBROUTINE ZTBMV(UPLO,TRANS,DIAG,N,K,A,LDA,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(INOUT) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE ZTBMV
END INTERFACE MKL77_TBMV

INTERFACE MKL77_TBSV
  PURE SUBROUTINE STBSV(UPLO,TRANS,DIAG,N,K,A,LDA,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(INOUT) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE STBSV
  PURE SUBROUTINE DTBSV(UPLO,TRANS,DIAG,N,K,A,LDA,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(INOUT) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE DTBSV
  PURE SUBROUTINE CTBSV(UPLO,TRANS,DIAG,N,K,A,LDA,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(INOUT) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE CTBSV
  PURE SUBROUTINE ZTBSV(UPLO,TRANS,DIAG,N,K,A,LDA,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(INOUT) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE ZTBSV
END INTERFACE MKL77_TBSV

INTERFACE MKL77_TPMV
  PURE SUBROUTINE STPMV(UPLO,TRANS,DIAG,N,A,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(IN) :: A(*)
    REAL(WP), INTENT(INOUT) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE STPMV
  PURE SUBROUTINE DTPMV(UPLO,TRANS,DIAG,N,A,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(IN) :: A(*)
    REAL(WP), INTENT(INOUT) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE DTPMV
  PURE SUBROUTINE CTPMV(UPLO,TRANS,DIAG,N,A,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(IN) :: A(*)
    COMPLEX(WP), INTENT(INOUT) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE CTPMV
  PURE SUBROUTINE ZTPMV(UPLO,TRANS,DIAG,N,A,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(IN) :: A(*)
    COMPLEX(WP), INTENT(INOUT) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE ZTPMV
END INTERFACE MKL77_TPMV

INTERFACE MKL77_TPSV
  PURE SUBROUTINE STPSV(UPLO,TRANS,DIAG,N,A,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(IN) :: A(*)
    REAL(WP), INTENT(INOUT) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE STPSV
  PURE SUBROUTINE DTPSV(UPLO,TRANS,DIAG,N,A,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(IN) :: A(*)
    REAL(WP), INTENT(INOUT) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE DTPSV
  PURE SUBROUTINE CTPSV(UPLO,TRANS,DIAG,N,A,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(IN) :: A(*)
    COMPLEX(WP), INTENT(INOUT) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE CTPSV
  PURE SUBROUTINE ZTPSV(UPLO,TRANS,DIAG,N,A,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(IN) :: A(*)
    COMPLEX(WP), INTENT(INOUT) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
  END SUBROUTINE ZTPSV
END INTERFACE MKL77_TPSV

INTERFACE MKL77_TRMV
  PURE SUBROUTINE STRMV(UPLO,TRANS,DIAG,N,A,LDA,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(INOUT) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE STRMV
  PURE SUBROUTINE DTRMV(UPLO,TRANS,DIAG,N,A,LDA,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(INOUT) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE DTRMV
  PURE SUBROUTINE CTRMV(UPLO,TRANS,DIAG,N,A,LDA,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(INOUT) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE CTRMV
  PURE SUBROUTINE ZTRMV(UPLO,TRANS,DIAG,N,A,LDA,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(INOUT) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE ZTRMV
END INTERFACE MKL77_TRMV

INTERFACE MKL77_TRSV
  PURE SUBROUTINE STRSV(UPLO,TRANS,DIAG,N,A,LDA,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(INOUT) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE STRSV
  PURE SUBROUTINE DTRSV(UPLO,TRANS,DIAG,N,A,LDA,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(INOUT) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE DTRSV
  PURE SUBROUTINE CTRSV(UPLO,TRANS,DIAG,N,A,LDA,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(INOUT) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE CTRSV
  PURE SUBROUTINE ZTRSV(UPLO,TRANS,DIAG,N,A,LDA,X,INCX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(INOUT) :: X(*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    INTEGER, INTENT(IN) :: INCX
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
  END SUBROUTINE ZTRSV
END INTERFACE MKL77_TRSV

INTERFACE MKL77_GEMM
  PURE SUBROUTINE SGEMM(TRANSA,TRANSB,M,N,K,ALPHA,A,LDA,B,LDB,BETA,C,   &
     &                                                              LDC)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(IN) :: B(LDB,*)
    REAL(WP), INTENT(INOUT) :: C(LDC,*)
    CHARACTER(LEN=1), INTENT(IN) :: TRANSA
    CHARACTER(LEN=1), INTENT(IN) :: TRANSB
    REAL(WP), INTENT(IN) :: ALPHA
    REAL(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDB
    INTEGER, INTENT(IN) :: LDC
  END SUBROUTINE SGEMM
  PURE SUBROUTINE DGEMM(TRANSA,TRANSB,M,N,K,ALPHA,A,LDA,B,LDB,BETA,C,   &
     &                                                              LDC)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(IN) :: B(LDB,*)
    REAL(WP), INTENT(INOUT) :: C(LDC,*)
    CHARACTER(LEN=1), INTENT(IN) :: TRANSA
    CHARACTER(LEN=1), INTENT(IN) :: TRANSB
    REAL(WP), INTENT(IN) :: ALPHA
    REAL(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDB
    INTEGER, INTENT(IN) :: LDC
  END SUBROUTINE DGEMM
  PURE SUBROUTINE CGEMM(TRANSA,TRANSB,M,N,K,ALPHA,A,LDA,B,LDB,BETA,C,   &
     &                                                              LDC)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: B(LDB,*)
    COMPLEX(WP), INTENT(INOUT) :: C(LDC,*)
    CHARACTER(LEN=1), INTENT(IN) :: TRANSA
    CHARACTER(LEN=1), INTENT(IN) :: TRANSB
    COMPLEX(WP), INTENT(IN) :: ALPHA
    COMPLEX(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDB
    INTEGER, INTENT(IN) :: LDC
  END SUBROUTINE CGEMM
  PURE SUBROUTINE ZGEMM(TRANSA,TRANSB,M,N,K,ALPHA,A,LDA,B,LDB,BETA,C,   &
     &                                                              LDC)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: B(LDB,*)
    COMPLEX(WP), INTENT(INOUT) :: C(LDC,*)
    CHARACTER(LEN=1), INTENT(IN) :: TRANSA
    CHARACTER(LEN=1), INTENT(IN) :: TRANSB
    COMPLEX(WP), INTENT(IN) :: ALPHA
    COMPLEX(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDB
    INTEGER, INTENT(IN) :: LDC
  END SUBROUTINE ZGEMM
END INTERFACE MKL77_GEMM

INTERFACE MKL77_HEMM
  PURE SUBROUTINE CHEMM(SIDE,UPLO,M,N,ALPHA,A,LDA,B,LDB,BETA,C,LDC)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: B(LDB,*)
    COMPLEX(WP), INTENT(INOUT) :: C(LDC,*)
    CHARACTER(LEN=1), INTENT(IN) :: SIDE
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    COMPLEX(WP), INTENT(IN) :: ALPHA
    COMPLEX(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDB
    INTEGER, INTENT(IN) :: LDC
  END SUBROUTINE CHEMM
  PURE SUBROUTINE ZHEMM(SIDE,UPLO,M,N,ALPHA,A,LDA,B,LDB,BETA,C,LDC)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: B(LDB,*)
    COMPLEX(WP), INTENT(INOUT) :: C(LDC,*)
    CHARACTER(LEN=1), INTENT(IN) :: SIDE
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    COMPLEX(WP), INTENT(IN) :: ALPHA
    COMPLEX(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDB
    INTEGER, INTENT(IN) :: LDC
  END SUBROUTINE ZHEMM
END INTERFACE MKL77_HEMM

INTERFACE MKL77_HERK
  PURE SUBROUTINE CHERK(UPLO,TRANS,N,K,ALPHA,A,LDA,BETA,C,LDC)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(INOUT) :: C(LDC,*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    REAL(WP), INTENT(IN) :: ALPHA
    REAL(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDC
  END SUBROUTINE CHERK
  PURE SUBROUTINE ZHERK(UPLO,TRANS,N,K,ALPHA,A,LDA,BETA,C,LDC)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(INOUT) :: C(LDC,*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    REAL(WP), INTENT(IN) :: ALPHA
    REAL(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDC
  END SUBROUTINE ZHERK
END INTERFACE MKL77_HERK

INTERFACE MKL77_HER2K
  PURE SUBROUTINE CHER2K(UPLO,TRANS,N,K,ALPHA,A,LDA,B,LDB,BETA,C,LDC)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: B(LDB,*)
    COMPLEX(WP), INTENT(INOUT) :: C(LDC,*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    COMPLEX(WP), INTENT(IN) :: ALPHA
    REAL(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDB
    INTEGER, INTENT(IN) :: LDC
  END SUBROUTINE CHER2K
  PURE SUBROUTINE ZHER2K(UPLO,TRANS,N,K,ALPHA,A,LDA,B,LDB,BETA,C,LDC)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: B(LDB,*)
    COMPLEX(WP), INTENT(INOUT) :: C(LDC,*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    COMPLEX(WP), INTENT(IN) :: ALPHA
    REAL(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDB
    INTEGER, INTENT(IN) :: LDC
  END SUBROUTINE ZHER2K
END INTERFACE MKL77_HER2K

INTERFACE MKL77_SYMM
  PURE SUBROUTINE SSYMM(SIDE,UPLO,M,N,ALPHA,A,LDA,B,LDB,BETA,C,LDC)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(IN) :: B(LDB,*)
    REAL(WP), INTENT(INOUT) :: C(LDC,*)
    CHARACTER(LEN=1), INTENT(IN) :: SIDE
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    REAL(WP), INTENT(IN) :: ALPHA
    REAL(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDB
    INTEGER, INTENT(IN) :: LDC
  END SUBROUTINE SSYMM
  PURE SUBROUTINE DSYMM(SIDE,UPLO,M,N,ALPHA,A,LDA,B,LDB,BETA,C,LDC)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(IN) :: B(LDB,*)
    REAL(WP), INTENT(INOUT) :: C(LDC,*)
    CHARACTER(LEN=1), INTENT(IN) :: SIDE
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    REAL(WP), INTENT(IN) :: ALPHA
    REAL(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDB
    INTEGER, INTENT(IN) :: LDC
  END SUBROUTINE DSYMM
  PURE SUBROUTINE CSYMM(SIDE,UPLO,M,N,ALPHA,A,LDA,B,LDB,BETA,C,LDC)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: B(LDB,*)
    COMPLEX(WP), INTENT(INOUT) :: C(LDC,*)
    CHARACTER(LEN=1), INTENT(IN) :: SIDE
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    COMPLEX(WP), INTENT(IN) :: ALPHA
    COMPLEX(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDB
    INTEGER, INTENT(IN) :: LDC
  END SUBROUTINE CSYMM
  PURE SUBROUTINE ZSYMM(SIDE,UPLO,M,N,ALPHA,A,LDA,B,LDB,BETA,C,LDC)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: B(LDB,*)
    COMPLEX(WP), INTENT(INOUT) :: C(LDC,*)
    CHARACTER(LEN=1), INTENT(IN) :: SIDE
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    COMPLEX(WP), INTENT(IN) :: ALPHA
    COMPLEX(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDB
    INTEGER, INTENT(IN) :: LDC
  END SUBROUTINE ZSYMM
END INTERFACE MKL77_SYMM

INTERFACE MKL77_SYRK
  PURE SUBROUTINE SSYRK(UPLO,TRANS,N,K,ALPHA,A,LDA,BETA,C,LDC)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(INOUT) :: C(LDC,*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    REAL(WP), INTENT(IN) :: ALPHA
    REAL(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDC
  END SUBROUTINE SSYRK
  PURE SUBROUTINE DSYRK(UPLO,TRANS,N,K,ALPHA,A,LDA,BETA,C,LDC)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(INOUT) :: C(LDC,*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    REAL(WP), INTENT(IN) :: ALPHA
    REAL(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDC
  END SUBROUTINE DSYRK
  PURE SUBROUTINE CSYRK(UPLO,TRANS,N,K,ALPHA,A,LDA,BETA,C,LDC)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(INOUT) :: C(LDC,*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    COMPLEX(WP), INTENT(IN) :: ALPHA
    COMPLEX(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDC
  END SUBROUTINE CSYRK
  PURE SUBROUTINE ZSYRK(UPLO,TRANS,N,K,ALPHA,A,LDA,BETA,C,LDC)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(INOUT) :: C(LDC,*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    COMPLEX(WP), INTENT(IN) :: ALPHA
    COMPLEX(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDC
  END SUBROUTINE ZSYRK
END INTERFACE MKL77_SYRK

INTERFACE MKL77_SYR2K
  PURE SUBROUTINE SSYR2K(UPLO,TRANS,N,K,ALPHA,A,LDA,B,LDB,BETA,C,LDC)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(IN) :: B(LDB,*)
    REAL(WP), INTENT(INOUT) :: C(LDC,*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    REAL(WP), INTENT(IN) :: ALPHA
    REAL(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDB
    INTEGER, INTENT(IN) :: LDC
  END SUBROUTINE SSYR2K
  PURE SUBROUTINE DSYR2K(UPLO,TRANS,N,K,ALPHA,A,LDA,B,LDB,BETA,C,LDC)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(IN) :: B(LDB,*)
    REAL(WP), INTENT(INOUT) :: C(LDC,*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    REAL(WP), INTENT(IN) :: ALPHA
    REAL(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDB
    INTEGER, INTENT(IN) :: LDC
  END SUBROUTINE DSYR2K
  PURE SUBROUTINE CSYR2K(UPLO,TRANS,N,K,ALPHA,A,LDA,B,LDB,BETA,C,LDC)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: B(LDB,*)
    COMPLEX(WP), INTENT(INOUT) :: C(LDC,*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    COMPLEX(WP), INTENT(IN) :: ALPHA
    COMPLEX(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDB
    INTEGER, INTENT(IN) :: LDC
  END SUBROUTINE CSYR2K
  PURE SUBROUTINE ZSYR2K(UPLO,TRANS,N,K,ALPHA,A,LDA,B,LDB,BETA,C,LDC)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(IN) :: B(LDB,*)
    COMPLEX(WP), INTENT(INOUT) :: C(LDC,*)
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANS
    COMPLEX(WP), INTENT(IN) :: ALPHA
    COMPLEX(WP), INTENT(IN) :: BETA
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: K
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDB
    INTEGER, INTENT(IN) :: LDC
  END SUBROUTINE ZSYR2K
END INTERFACE MKL77_SYR2K

INTERFACE MKL77_TRMM
  PURE SUBROUTINE STRMM(SIDE,UPLO,TRANSA,DIAG,M,N,ALPHA,A,LDA,B,LDB)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(INOUT) :: B(LDB,*)
    CHARACTER(LEN=1), INTENT(IN) :: SIDE
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANSA
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    REAL(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDB
  END SUBROUTINE STRMM
  PURE SUBROUTINE DTRMM(SIDE,UPLO,TRANSA,DIAG,M,N,ALPHA,A,LDA,B,LDB)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(INOUT) :: B(LDB,*)
    CHARACTER(LEN=1), INTENT(IN) :: SIDE
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANSA
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    REAL(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDB
  END SUBROUTINE DTRMM
  PURE SUBROUTINE CTRMM(SIDE,UPLO,TRANSA,DIAG,M,N,ALPHA,A,LDA,B,LDB)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(INOUT) :: B(LDB,*)
    CHARACTER(LEN=1), INTENT(IN) :: SIDE
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANSA
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    COMPLEX(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDB
  END SUBROUTINE CTRMM
  PURE SUBROUTINE ZTRMM(SIDE,UPLO,TRANSA,DIAG,M,N,ALPHA,A,LDA,B,LDB)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(INOUT) :: B(LDB,*)
    CHARACTER(LEN=1), INTENT(IN) :: SIDE
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANSA
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    COMPLEX(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDB
  END SUBROUTINE ZTRMM
END INTERFACE MKL77_TRMM

INTERFACE MKL77_TRSM
  PURE SUBROUTINE STRSM(SIDE,UPLO,TRANSA,DIAG,M,N,ALPHA,A,LDA,B,LDB)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(INOUT) :: B(LDB,*)
    CHARACTER(LEN=1), INTENT(IN) :: SIDE
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANSA
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    REAL(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDB
  END SUBROUTINE STRSM
  PURE SUBROUTINE DTRSM(SIDE,UPLO,TRANSA,DIAG,M,N,ALPHA,A,LDA,B,LDB)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(IN) :: A(LDA,*)
    REAL(WP), INTENT(INOUT) :: B(LDB,*)
    CHARACTER(LEN=1), INTENT(IN) :: SIDE
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANSA
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    REAL(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDB
  END SUBROUTINE DTRSM
  PURE SUBROUTINE CTRSM(SIDE,UPLO,TRANSA,DIAG,M,N,ALPHA,A,LDA,B,LDB)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(INOUT) :: B(LDB,*)
    CHARACTER(LEN=1), INTENT(IN) :: SIDE
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANSA
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    COMPLEX(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDB
  END SUBROUTINE CTRSM
  PURE SUBROUTINE ZTRSM(SIDE,UPLO,TRANSA,DIAG,M,N,ALPHA,A,LDA,B,LDB)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(IN) :: A(LDA,*)
    COMPLEX(WP), INTENT(INOUT) :: B(LDB,*)
    CHARACTER(LEN=1), INTENT(IN) :: SIDE
    CHARACTER(LEN=1), INTENT(IN) :: UPLO
    CHARACTER(LEN=1), INTENT(IN) :: TRANSA
    CHARACTER(LEN=1), INTENT(IN) :: DIAG
    COMPLEX(WP), INTENT(IN) :: ALPHA
    INTEGER, INTENT(IN) :: M
    INTEGER, INTENT(IN) :: N
    INTEGER, INTENT(IN) :: LDA
    INTEGER, INTENT(IN) :: LDB
  END SUBROUTINE ZTRSM
END INTERFACE MKL77_TRSM

INTERFACE MKL77_AXPYI
  PURE SUBROUTINE SAXPYI(NZ,A,X,INDX,Y)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INDX(*)
    REAL(WP), INTENT(INOUT) :: Y(*)
    REAL(WP), INTENT(IN) :: A
    INTEGER, INTENT(IN) :: NZ
  END SUBROUTINE SAXPYI
  PURE SUBROUTINE DAXPYI(NZ,A,X,INDX,Y)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INDX(*)
    REAL(WP), INTENT(INOUT) :: Y(*)
    REAL(WP), INTENT(IN) :: A
    INTEGER, INTENT(IN) :: NZ
  END SUBROUTINE DAXPYI
  PURE SUBROUTINE CAXPYI(NZ,A,X,INDX,Y)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INDX(*)
    COMPLEX(WP), INTENT(INOUT) :: Y(*)
    COMPLEX(WP), INTENT(IN) :: A
    INTEGER, INTENT(IN) :: NZ
  END SUBROUTINE CAXPYI
  PURE SUBROUTINE ZAXPYI(NZ,A,X,INDX,Y)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INDX(*)
    COMPLEX(WP), INTENT(INOUT) :: Y(*)
    COMPLEX(WP), INTENT(IN) :: A
    INTEGER, INTENT(IN) :: NZ
  END SUBROUTINE ZAXPYI
END INTERFACE MKL77_AXPYI

INTERFACE MKL77_DOTI
  PURE FUNCTION SDOTI(NZ,X,INDX,Y)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP) :: SDOTI
    REAL(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INDX(*)
    REAL(WP), INTENT(IN) :: Y(*)
    INTEGER, INTENT(IN) :: NZ
  END FUNCTION SDOTI
  PURE FUNCTION DDOTI(NZ,X,INDX,Y)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP) :: DDOTI
    REAL(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INDX(*)
    REAL(WP), INTENT(IN) :: Y(*)
    INTEGER, INTENT(IN) :: NZ
  END FUNCTION DDOTI
END INTERFACE MKL77_DOTI

INTERFACE MKL77_DOTCI
  PURE FUNCTION CDOTCI(NZ,X,INDX,Y)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP) :: CDOTCI
    COMPLEX(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INDX(*)
    COMPLEX(WP), INTENT(IN) :: Y(*)
    INTEGER, INTENT(IN) :: NZ
  END FUNCTION CDOTCI
  PURE FUNCTION ZDOTCI(NZ,X,INDX,Y)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP) :: ZDOTCI
    COMPLEX(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INDX(*)
    COMPLEX(WP), INTENT(IN) :: Y(*)
    INTEGER, INTENT(IN) :: NZ
  END FUNCTION ZDOTCI
END INTERFACE MKL77_DOTCI

INTERFACE MKL77_DOTUI
  PURE FUNCTION CDOTUI(NZ,X,INDX,Y)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP) :: CDOTUI
    COMPLEX(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INDX(*)
    COMPLEX(WP), INTENT(IN) :: Y(*)
    INTEGER, INTENT(IN) :: NZ
  END FUNCTION CDOTUI
  PURE FUNCTION ZDOTUI(NZ,X,INDX,Y)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP) :: ZDOTUI
    COMPLEX(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INDX(*)
    COMPLEX(WP), INTENT(IN) :: Y(*)
    INTEGER, INTENT(IN) :: NZ
  END FUNCTION ZDOTUI
END INTERFACE MKL77_DOTUI

INTERFACE MKL77_GTHR
  PURE SUBROUTINE SGTHR(NZ,Y,X,INDX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(OUT) :: X(*)
    INTEGER, INTENT(IN) :: INDX(*)
    REAL(WP), INTENT(IN) :: Y(*)
    INTEGER, INTENT(IN) :: NZ
  END SUBROUTINE SGTHR
  PURE SUBROUTINE DGTHR(NZ,Y,X,INDX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(OUT) :: X(*)
    INTEGER, INTENT(IN) :: INDX(*)
    REAL(WP), INTENT(IN) :: Y(*)
    INTEGER, INTENT(IN) :: NZ
  END SUBROUTINE DGTHR
  PURE SUBROUTINE CGTHR(NZ,Y,X,INDX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(OUT) :: X(*)
    INTEGER, INTENT(IN) :: INDX(*)
    COMPLEX(WP), INTENT(IN) :: Y(*)
    INTEGER, INTENT(IN) :: NZ
  END SUBROUTINE CGTHR
  PURE SUBROUTINE ZGTHR(NZ,Y,X,INDX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(OUT) :: X(*)
    INTEGER, INTENT(IN) :: INDX(*)
    COMPLEX(WP), INTENT(IN) :: Y(*)
    INTEGER, INTENT(IN) :: NZ
  END SUBROUTINE ZGTHR
END INTERFACE MKL77_GTHR

INTERFACE MKL77_GTHRZ
  PURE SUBROUTINE SGTHRZ(NZ,Y,X,INDX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(OUT) :: X(*)
    INTEGER, INTENT(IN) :: INDX(*)
    REAL(WP), INTENT(INOUT) :: Y(*)
    INTEGER, INTENT(IN) :: NZ
  END SUBROUTINE SGTHRZ
  PURE SUBROUTINE DGTHRZ(NZ,Y,X,INDX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(OUT) :: X(*)
    INTEGER, INTENT(IN) :: INDX(*)
    REAL(WP), INTENT(INOUT) :: Y(*)
    INTEGER, INTENT(IN) :: NZ
  END SUBROUTINE DGTHRZ
  PURE SUBROUTINE CGTHRZ(NZ,Y,X,INDX)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(OUT) :: X(*)
    INTEGER, INTENT(IN) :: INDX(*)
    COMPLEX(WP), INTENT(INOUT) :: Y(*)
    INTEGER, INTENT(IN) :: NZ
  END SUBROUTINE CGTHRZ
  PURE SUBROUTINE ZGTHRZ(NZ,Y,X,INDX)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(OUT) :: X(*)
    INTEGER, INTENT(IN) :: INDX(*)
    COMPLEX(WP), INTENT(INOUT) :: Y(*)
    INTEGER, INTENT(IN) :: NZ
  END SUBROUTINE ZGTHRZ
END INTERFACE MKL77_GTHRZ

INTERFACE MKL77_ROTI
  PURE SUBROUTINE SROTI(NZ,X,INDX,Y,C,S)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(INOUT) :: X(*)
    INTEGER, INTENT(IN) :: INDX(*)
    REAL(WP), INTENT(IN) :: Y(*)
    REAL(WP), INTENT(IN) :: C
    REAL(WP), INTENT(IN) :: S
    INTEGER, INTENT(IN) :: NZ
  END SUBROUTINE SROTI
  PURE SUBROUTINE DROTI(NZ,X,INDX,Y,C,S)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(INOUT) :: X(*)
    INTEGER, INTENT(IN) :: INDX(*)
    REAL(WP), INTENT(IN) :: Y(*)
    REAL(WP), INTENT(IN) :: C
    REAL(WP), INTENT(IN) :: S
    INTEGER, INTENT(IN) :: NZ
  END SUBROUTINE DROTI
END INTERFACE MKL77_ROTI

INTERFACE MKL77_SCTR
  PURE SUBROUTINE SSCTR(NZ,X,INDX,Y)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    REAL(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INDX(*)
    REAL(WP), INTENT(OUT) :: Y(*)
    INTEGER, INTENT(IN) :: NZ
  END SUBROUTINE SSCTR
  PURE SUBROUTINE DSCTR(NZ,X,INDX,Y)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    REAL(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INDX(*)
    REAL(WP), INTENT(OUT) :: Y(*)
    INTEGER, INTENT(IN) :: NZ
  END SUBROUTINE DSCTR
  PURE SUBROUTINE CSCTR(NZ,X,INDX,Y)
    INTEGER, PARAMETER :: WP = KIND(1.0E0)
    COMPLEX(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INDX(*)
    COMPLEX(WP), INTENT(OUT) :: Y(*)
    INTEGER, INTENT(IN) :: NZ
  END SUBROUTINE CSCTR
  PURE SUBROUTINE ZSCTR(NZ,X,INDX,Y)
    INTEGER, PARAMETER :: WP = KIND(1.0D0)
    COMPLEX(WP), INTENT(IN) :: X(*)
    INTEGER, INTENT(IN) :: INDX(*)
    COMPLEX(WP), INTENT(OUT) :: Y(*)
    INTEGER, INTENT(IN) :: NZ
  END SUBROUTINE ZSCTR
END INTERFACE MKL77_SCTR

END MODULE MKL77_BLAS
